//! KVM VMI ioctl numbers and constants not generated by bindgen.
//!
//! Simple `#define` constants (event types, access flags, response flags, etc.)
//! are generated by bindgen and live in `kvm_sys`. This module only contains:
//! - Page constants (not in any header)
//! - Ioctl numbers (`_IO`/`_IOW`/`_IOR`/`_IOWR` macros that bindgen can't process)
//! - Capabilities (from `linux/kvm.h`, not included in our bindgen wrapper)

/// Page size (4 KiB).
pub const PAGE_SIZE: u64 = 0x1000;

/// Page shift (12 bits).
pub const PAGE_SHIFT: u64 = 12;

/// Invalid GFN sentinel (revert to host mapping).
/// Equivalent to `KVM_VMI_INVALID_GFN` in the kernel header (`~(__u64)0`),
/// which bindgen cannot process.
pub const INVALID_GFN: u64 = !0u64;

// ---------------------------------------------------------------------------
// ioctl helpers
// ---------------------------------------------------------------------------

const KVMIO: u32 = 0xAE;

pub(crate) const fn _io(nr: u32) -> libc::c_ulong {
    ((KVMIO << 8) | nr) as libc::c_ulong
}

pub(crate) const fn _iow<T>(nr: u32) -> libc::c_ulong {
    let size = std::mem::size_of::<T>() as u32;
    ((1u32) << 30 | (size << 16) | (KVMIO << 8) | nr) as libc::c_ulong
}

pub(crate) const fn _ior<T>(nr: u32) -> libc::c_ulong {
    let size = std::mem::size_of::<T>() as u32;
    ((2u32) << 30 | (size << 16) | (KVMIO << 8) | nr) as libc::c_ulong
}

pub(crate) const fn _iowr<T>(nr: u32) -> libc::c_ulong {
    let size = std::mem::size_of::<T>() as u32;
    ((3u32) << 30 | (size << 16) | (KVMIO << 8) | nr) as libc::c_ulong
}

// ---------------------------------------------------------------------------
// VM-level ioctl
// ---------------------------------------------------------------------------

pub const KVM_CREATE_VMI: libc::c_ulong = _io(0xef);

// ---------------------------------------------------------------------------
// vCPU-level ioctls (for register access on duplicated vCPU fds)
// These come from linux/kvm.h, not kvm_vmi.h.
// ---------------------------------------------------------------------------

// KVM_GET_REGS: _IOR(KVMIO, 0x81, struct kvm_regs) -- struct kvm_regs is 144 bytes
pub const KVM_GET_REGS: libc::c_ulong =
    ((2u32 << 30) | (144u32 << 16) | (KVMIO << 8) | 0x81) as libc::c_ulong;
pub const KVM_SET_REGS: libc::c_ulong =
    ((1u32 << 30) | (144u32 << 16) | (KVMIO << 8) | 0x82) as libc::c_ulong;

// KVM_GET_SREGS: _IOR(KVMIO, 0x83, struct kvm_sregs) -- struct kvm_sregs is 312 bytes
pub const KVM_GET_SREGS: libc::c_ulong =
    ((2u32 << 30) | (312u32 << 16) | (KVMIO << 8) | 0x83) as libc::c_ulong;
pub const KVM_SET_SREGS: libc::c_ulong =
    ((1u32 << 30) | (312u32 << 16) | (KVMIO << 8) | 0x84) as libc::c_ulong;

pub const KVM_CHECK_EXTENSION: libc::c_ulong = _io(0x04);

// ---------------------------------------------------------------------------
// vmi_fd ioctls -- sizes computed from bindgen-generated struct types
// ---------------------------------------------------------------------------

pub const KVM_VMI_CONTROL_EVENT: libc::c_ulong =
    _iow::<kvm_sys::kvm_vmi_control_event>(0xd6);
pub const KVM_VMI_ACK_EVENT: libc::c_ulong =
    _iow::<kvm_sys::kvm_vmi_vcpu>(0xd7);
pub const KVM_VMI_SETUP_RING: libc::c_ulong =
    _iowr::<kvm_sys::kvm_vmi_setup_ring>(0xd8);
pub const KVM_VMI_TEARDOWN_RING: libc::c_ulong =
    _iow::<u32>(0xd9);
pub const KVM_VMI_CREATE_VIEW: libc::c_ulong =
    _iowr::<kvm_sys::kvm_vmi_view>(0xda);
pub const KVM_VMI_DESTROY_VIEW: libc::c_ulong =
    _iow::<kvm_sys::kvm_vmi_view>(0xdb);
pub const KVM_VMI_SWITCH_VIEW: libc::c_ulong =
    _iow::<kvm_sys::kvm_vmi_switch_view>(0xdc);
pub const KVM_VMI_GET_MEM_ACCESS: libc::c_ulong =
    _iowr::<kvm_sys::kvm_vmi_mem_access>(0xdd);
pub const KVM_VMI_SET_MEM_ACCESS: libc::c_ulong =
    _iow::<kvm_sys::kvm_vmi_mem_access>(0xde);
pub const KVM_VMI_PAUSE_VM: libc::c_ulong = _io(0xdf);
pub const KVM_VMI_UNPAUSE_VM: libc::c_ulong = _io(0xe0);
pub const KVM_VMI_PAUSE_VCPU: libc::c_ulong =
    _iow::<kvm_sys::kvm_vmi_vcpu>(0xe1);
pub const KVM_VMI_UNPAUSE_VCPU: libc::c_ulong =
    _iow::<kvm_sys::kvm_vmi_vcpu>(0xe2);
pub const KVM_VMI_INJECT_EVENT: libc::c_ulong =
    _iow::<kvm_sys::kvm_vmi_inject_event>(0xe3);
pub const KVM_VMI_SINGLESTEP: libc::c_ulong =
    _iow::<kvm_sys::kvm_vmi_singlestep>(0xe4);
pub const KVM_VMI_ALLOC_GFN: libc::c_ulong =
    _iowr::<kvm_sys::kvm_vmi_alloc_gfn>(0xe5);
pub const KVM_VMI_FREE_GFN: libc::c_ulong =
    _iow::<kvm_sys::kvm_vmi_free_gfn>(0xe6);
pub const KVM_VMI_CHANGE_GFN: libc::c_ulong =
    _iow::<kvm_sys::kvm_vmi_change_gfn>(0xe7);

// ---------------------------------------------------------------------------
// Capabilities (from linux/kvm.h, not in our bindgen wrapper)
// ---------------------------------------------------------------------------

pub const KVM_CAP_VMI: u32 = 248;
pub const KVM_CAP_VMI_RING: u32 = 260;
pub const KVM_CAP_VMI_GUEST_MMAP: u32 = 261;
pub const KVM_CAP_VMI_PAUSE: u32 = 262;
pub const KVM_CAP_VMI_INJECT: u32 = 263;
pub const KVM_CAP_VMI_ALLOC_GFN: u32 = 264;
pub const KVM_CAP_NR_VCPUS: u32 = 9;
pub const KVM_CAP_MAX_VCPUS: u32 = 66;
pub const KVM_CAP_NR_MEMSLOTS: u32 = 10;
