//! KVM VMI constants.
//!
//! Ioctl numbers, capability constants, and simple `#define` values are all
//! generated by bindgen and live in `kvm_sys`.  This module re-exports them
//! under shorter names and provides page-level constants that are not in any
//! kernel header.

/// Page size (4 KiB).
pub const PAGE_SIZE: u64 = 0x1000;

/// Page shift (12 bits).
pub const PAGE_SHIFT: u64 = 12;

/// Invalid GFN sentinel (revert to host mapping).
/// Equivalent to `KVM_VMI_INVALID_GFN` in the kernel header (`~(__u64)0`),
/// which bindgen cannot process.
pub const INVALID_GFN: u64 = !0u64;

// ---------------------------------------------------------------------------
// Ioctl numbers — derived from kernel headers via bindgen.
//
// The _IOCTL suffix in kvm_sys comes from the static-const trick in
// wrapper.h (needed because bindgen cannot evaluate #define macros that
// contain sizeof).  We re-export them here without the suffix.
// ---------------------------------------------------------------------------

/// VM-level ioctl: create VMI session, returns vmi_fd.
pub const KVM_CREATE_VMI: libc::c_ulong = kvm_sys::KVM_CREATE_VMI_IOCTL;

// vmi_fd ioctls (ordered to match uAPI header)
pub const KVM_VMI_SETUP_RING: libc::c_ulong = kvm_sys::KVM_VMI_SETUP_RING_IOCTL;
pub const KVM_VMI_TEARDOWN_RING: libc::c_ulong = kvm_sys::KVM_VMI_TEARDOWN_RING_IOCTL;
pub const KVM_VMI_CONTROL_EVENT: libc::c_ulong = kvm_sys::KVM_VMI_CONTROL_EVENT_IOCTL;
pub const KVM_VMI_ACK_EVENT: libc::c_ulong = kvm_sys::KVM_VMI_ACK_EVENT_IOCTL;
pub const KVM_VMI_CREATE_VIEW: libc::c_ulong = kvm_sys::KVM_VMI_CREATE_VIEW_IOCTL;
pub const KVM_VMI_DESTROY_VIEW: libc::c_ulong = kvm_sys::KVM_VMI_DESTROY_VIEW_IOCTL;
pub const KVM_VMI_SWITCH_VIEW: libc::c_ulong = kvm_sys::KVM_VMI_SWITCH_VIEW_IOCTL;
pub const KVM_VMI_GET_MEM_ACCESS: libc::c_ulong = kvm_sys::KVM_VMI_GET_MEM_ACCESS_IOCTL;
pub const KVM_VMI_SET_MEM_ACCESS: libc::c_ulong = kvm_sys::KVM_VMI_SET_MEM_ACCESS_IOCTL;
pub const KVM_VMI_ALLOC_GFN: libc::c_ulong = kvm_sys::KVM_VMI_ALLOC_GFN_IOCTL;
pub const KVM_VMI_FREE_GFN: libc::c_ulong = kvm_sys::KVM_VMI_FREE_GFN_IOCTL;
pub const KVM_VMI_CHANGE_GFN: libc::c_ulong = kvm_sys::KVM_VMI_CHANGE_GFN_IOCTL;
pub const KVM_VMI_PAUSE_VM: libc::c_ulong = kvm_sys::KVM_VMI_PAUSE_VM_IOCTL;
pub const KVM_VMI_UNPAUSE_VM: libc::c_ulong = kvm_sys::KVM_VMI_UNPAUSE_VM_IOCTL;
pub const KVM_VMI_PAUSE_VCPU: libc::c_ulong = kvm_sys::KVM_VMI_PAUSE_VCPU_IOCTL;
pub const KVM_VMI_UNPAUSE_VCPU: libc::c_ulong = kvm_sys::KVM_VMI_UNPAUSE_VCPU_IOCTL;
pub const KVM_VMI_INJECT_EVENT: libc::c_ulong = kvm_sys::KVM_VMI_INJECT_EVENT_IOCTL;

// vCPU-level ioctls (register access via duplicated vCPU fds)
pub const KVM_GET_REGS: libc::c_ulong = kvm_sys::KVM_GET_REGS_IOCTL;
pub const KVM_SET_REGS: libc::c_ulong = kvm_sys::KVM_SET_REGS_IOCTL;
pub const KVM_GET_SREGS: libc::c_ulong = kvm_sys::KVM_GET_SREGS_IOCTL;
pub const KVM_SET_SREGS: libc::c_ulong = kvm_sys::KVM_SET_SREGS_IOCTL;
pub const KVM_GET_MSRS: libc::c_ulong = kvm_sys::KVM_GET_MSRS_IOCTL;
pub const KVM_SET_MSRS: libc::c_ulong = kvm_sys::KVM_SET_MSRS_IOCTL;
pub const KVM_CHECK_EXTENSION: libc::c_ulong = kvm_sys::KVM_CHECK_EXTENSION_IOCTL;

// ---------------------------------------------------------------------------
// Capabilities — also from bindgen (linux/kvm.h constants).
// Re-exported here for convenience.
// ---------------------------------------------------------------------------

pub const KVM_CAP_VMI: u32 = kvm_sys::KVM_CAP_VMI;
pub const KVM_CAP_VMI_RING: u32 = kvm_sys::KVM_CAP_VMI_RING;
pub const KVM_CAP_VMI_GUEST_MMAP: u32 = kvm_sys::KVM_CAP_VMI_GUEST_MMAP;
pub const KVM_CAP_VMI_PAUSE: u32 = kvm_sys::KVM_CAP_VMI_PAUSE;
pub const KVM_CAP_VMI_INJECT: u32 = kvm_sys::KVM_CAP_VMI_INJECT;
pub const KVM_CAP_VMI_ALLOC_GFN: u32 = kvm_sys::KVM_CAP_VMI_ALLOC_GFN;
pub const KVM_CAP_NR_VCPUS: u32 = kvm_sys::KVM_CAP_NR_VCPUS;
pub const KVM_CAP_MAX_VCPUS: u32 = kvm_sys::KVM_CAP_MAX_VCPUS;
pub const KVM_CAP_NR_MEMSLOTS: u32 = kvm_sys::KVM_CAP_NR_MEMSLOTS;
