/* automatically generated by rust-bindgen 0.72.1 */

pub const KVM_CAP_NR_VCPUS: u32 = 9;
pub const KVM_CAP_NR_MEMSLOTS: u32 = 10;
pub const KVM_CAP_MAX_VCPUS: u32 = 66;
pub const KVM_CAP_VMI: u32 = 248;
pub const KVM_CAP_VMI_RING: u32 = 260;
pub const KVM_CAP_VMI_GUEST_MMAP: u32 = 261;
pub const KVM_CAP_VMI_PAUSE: u32 = 262;
pub const KVM_CAP_VMI_INJECT: u32 = 263;
pub const KVM_CAP_VMI_ALLOC_GFN: u32 = 264;
pub const KVM_CAP_VMI_EPT_PW: u32 = 265;
pub const KVM_VMI_EVENT_MEM_ACCESS: u32 = 0;
pub const KVM_VMI_EVENT_SINGLESTEP: u32 = 1;
pub const KVM_VMI_EVENT_ARCH_BASE: u32 = 8;
pub const KVM_VMI_NUM_EVENTS: u32 = 10;
pub const KVM_VMI_ARM64_SYSREG_SCTLR_EL1: u32 = 0;
pub const KVM_VMI_ARM64_SYSREG_TTBR0_EL1: u32 = 1;
pub const KVM_VMI_ARM64_SYSREG_TTBR1_EL1: u32 = 2;
pub const KVM_VMI_ARM64_SYSREG_TCR_EL1: u32 = 3;
pub const KVM_VMI_ARM64_INJECT_SYNC: u32 = 0;
pub const KVM_VMI_ARM64_INJECT_SERROR: u32 = 1;
pub const KVM_VMI_ACCESS_R: u32 = 1;
pub const KVM_VMI_ACCESS_W: u32 = 2;
pub const KVM_VMI_ACCESS_X: u32 = 4;
pub const KVM_VMI_ACCESS_PW: u32 = 8;
pub const KVM_VMI_ACCESS_RW: u32 = 3;
pub const KVM_VMI_ACCESS_RX: u32 = 5;
pub const KVM_VMI_ACCESS_WX: u32 = 6;
pub const KVM_VMI_ACCESS_RWX: u32 = 7;
pub const KVM_VMI_ACCESS_DEFAULT: u32 = 255;
pub const KVM_VMI_SHADOW_GFN_BASE: u64 = 281474943156224;
pub const KVM_VMI_RESPONSE_CONTINUE: u32 = 0;
pub const KVM_VMI_RESPONSE_DENY: u32 = 1;
pub const KVM_VMI_RESPONSE_SET_REGS: u32 = 2;
pub const KVM_VMI_RESPONSE_SINGLESTEP: u32 = 4;
pub const KVM_VMI_RESPONSE_SINGLESTEP_FAST: u32 = 8;
pub const KVM_VMI_RESPONSE_SWITCH_VIEW: u32 = 16;
pub const KVM_VMI_RESPONSE_EMULATE: u32 = 32;
pub const KVM_VMI_RESPONSE_REINJECT: u32 = 64;
pub const KVM_VMI_RESPONSE_MASK: u32 = 127;
pub type __u8 = ::std::os::raw::c_uchar;
pub type __u16 = ::std::os::raw::c_ushort;
pub type __s32 = ::std::os::raw::c_int;
pub type __u32 = ::std::os::raw::c_uint;
pub type __u64 = ::std::os::raw::c_ulonglong;
#[doc = " struct kvm_vmi_regs - arm64 register snapshot in ring events\n\n Captured by kernel on event delivery, optionally modified by agent\n via KVM_VMI_RESPONSE_SET_REGS. System registers are read-only -\n modifications are ignored on restore."]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_regs {
    pub regs: [__u64; 31usize],
    pub sp: __u64,
    pub pc: __u64,
    pub pstate: __u64,
    pub sctlr_el1: __u64,
    pub ttbr0_el1: __u64,
    pub ttbr1_el1: __u64,
    pub tcr_el1: __u64,
    pub esr_el1: __u64,
    pub far_el1: __u64,
    pub mair_el1: __u64,
    pub contextidr_el1: __u64,
    pub vbar_el1: __u64,
    pub tpidr_el1: __u64,
    pub sp_el0: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_regs"][::std::mem::size_of::<kvm_vmi_regs>() - 360usize];
    ["Alignment of kvm_vmi_regs"][::std::mem::align_of::<kvm_vmi_regs>() - 8usize];
    ["Offset of field: kvm_vmi_regs::regs"][::std::mem::offset_of!(kvm_vmi_regs, regs) - 0usize];
    ["Offset of field: kvm_vmi_regs::sp"][::std::mem::offset_of!(kvm_vmi_regs, sp) - 248usize];
    ["Offset of field: kvm_vmi_regs::pc"][::std::mem::offset_of!(kvm_vmi_regs, pc) - 256usize];
    ["Offset of field: kvm_vmi_regs::pstate"]
        [::std::mem::offset_of!(kvm_vmi_regs, pstate) - 264usize];
    ["Offset of field: kvm_vmi_regs::sctlr_el1"]
        [::std::mem::offset_of!(kvm_vmi_regs, sctlr_el1) - 272usize];
    ["Offset of field: kvm_vmi_regs::ttbr0_el1"]
        [::std::mem::offset_of!(kvm_vmi_regs, ttbr0_el1) - 280usize];
    ["Offset of field: kvm_vmi_regs::ttbr1_el1"]
        [::std::mem::offset_of!(kvm_vmi_regs, ttbr1_el1) - 288usize];
    ["Offset of field: kvm_vmi_regs::tcr_el1"]
        [::std::mem::offset_of!(kvm_vmi_regs, tcr_el1) - 296usize];
    ["Offset of field: kvm_vmi_regs::esr_el1"]
        [::std::mem::offset_of!(kvm_vmi_regs, esr_el1) - 304usize];
    ["Offset of field: kvm_vmi_regs::far_el1"]
        [::std::mem::offset_of!(kvm_vmi_regs, far_el1) - 312usize];
    ["Offset of field: kvm_vmi_regs::mair_el1"]
        [::std::mem::offset_of!(kvm_vmi_regs, mair_el1) - 320usize];
    ["Offset of field: kvm_vmi_regs::contextidr_el1"]
        [::std::mem::offset_of!(kvm_vmi_regs, contextidr_el1) - 328usize];
    ["Offset of field: kvm_vmi_regs::vbar_el1"]
        [::std::mem::offset_of!(kvm_vmi_regs, vbar_el1) - 336usize];
    ["Offset of field: kvm_vmi_regs::tpidr_el1"]
        [::std::mem::offset_of!(kvm_vmi_regs, tpidr_el1) - 344usize];
    ["Offset of field: kvm_vmi_regs::sp_el0"]
        [::std::mem::offset_of!(kvm_vmi_regs, sp_el0) - 352usize];
};
#[doc = " struct kvm_vmi_event_breakpoint - BRK software breakpoint event data\n @pc: Program counter (virtual address) of the BRK instruction.\n @gpa: Guest physical address of the BRK instruction.\n @comment: Immediate value from BRK #imm16 (ESR_EL2 bits [15:0])."]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_event_breakpoint {
    pub pc: __u64,
    pub gpa: __u64,
    pub comment: __u16,
    pub pad: [__u16; 3usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_event_breakpoint"]
        [::std::mem::size_of::<kvm_vmi_event_breakpoint>() - 24usize];
    ["Alignment of kvm_vmi_event_breakpoint"]
        [::std::mem::align_of::<kvm_vmi_event_breakpoint>() - 8usize];
    ["Offset of field: kvm_vmi_event_breakpoint::pc"]
        [::std::mem::offset_of!(kvm_vmi_event_breakpoint, pc) - 0usize];
    ["Offset of field: kvm_vmi_event_breakpoint::gpa"]
        [::std::mem::offset_of!(kvm_vmi_event_breakpoint, gpa) - 8usize];
    ["Offset of field: kvm_vmi_event_breakpoint::comment"]
        [::std::mem::offset_of!(kvm_vmi_event_breakpoint, comment) - 16usize];
    ["Offset of field: kvm_vmi_event_breakpoint::pad"]
        [::std::mem::offset_of!(kvm_vmi_event_breakpoint, pad) - 18usize];
};
#[doc = " struct kvm_vmi_event_sysreg - system register write event data\n @reg: KVM_VMI_ARM64_SYSREG_* index of the register being written.\n @old_value: Value before the write.\n @new_value: Value the guest is writing (after masking).\n\n Delivered when HCR_EL2.TVM traps a guest system register write.\n Agent responds CONTINUE to allow or DENY to discard the write."]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_event_sysreg {
    pub reg: __u32,
    pub pad: __u32,
    pub old_value: __u64,
    pub new_value: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_event_sysreg"][::std::mem::size_of::<kvm_vmi_event_sysreg>() - 24usize];
    ["Alignment of kvm_vmi_event_sysreg"][::std::mem::align_of::<kvm_vmi_event_sysreg>() - 8usize];
    ["Offset of field: kvm_vmi_event_sysreg::reg"]
        [::std::mem::offset_of!(kvm_vmi_event_sysreg, reg) - 0usize];
    ["Offset of field: kvm_vmi_event_sysreg::pad"]
        [::std::mem::offset_of!(kvm_vmi_event_sysreg, pad) - 4usize];
    ["Offset of field: kvm_vmi_event_sysreg::old_value"]
        [::std::mem::offset_of!(kvm_vmi_event_sysreg, old_value) - 8usize];
    ["Offset of field: kvm_vmi_event_sysreg::new_value"]
        [::std::mem::offset_of!(kvm_vmi_event_sysreg, new_value) - 16usize];
};
#[doc = " union kvm_vmi_arch_event_data - arm64-specific event data in ring events"]
#[repr(C)]
#[derive(Copy, Clone)]
pub union kvm_vmi_arch_event_data {
    pub breakpoint: kvm_vmi_event_breakpoint,
    pub sysreg: kvm_vmi_event_sysreg,
    pub pad: [__u8; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_arch_event_data"][::std::mem::size_of::<kvm_vmi_arch_event_data>() - 32usize];
    ["Alignment of kvm_vmi_arch_event_data"]
        [::std::mem::align_of::<kvm_vmi_arch_event_data>() - 8usize];
    ["Offset of field: kvm_vmi_arch_event_data::breakpoint"]
        [::std::mem::offset_of!(kvm_vmi_arch_event_data, breakpoint) - 0usize];
    ["Offset of field: kvm_vmi_arch_event_data::sysreg"]
        [::std::mem::offset_of!(kvm_vmi_arch_event_data, sysreg) - 0usize];
    ["Offset of field: kvm_vmi_arch_event_data::pad"]
        [::std::mem::offset_of!(kvm_vmi_arch_event_data, pad) - 0usize];
};
impl Default for kvm_vmi_arch_event_data {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[doc = " struct kvm_vmi_inject_event - arm64 event injection\n @vcpu_id: Target vCPU (must match ioctl's implied vCPU).\n @type: KVM_VMI_ARM64_INJECT_SYNC or KVM_VMI_ARM64_INJECT_SERROR.\n @esr: For SYNC: full ESR value (EC + IL + ISS).\n       For SERROR: ISS portion (bits [24:0])."]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_inject_event {
    pub vcpu_id: __u32,
    pub type_: __u32,
    pub esr: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_inject_event"][::std::mem::size_of::<kvm_vmi_inject_event>() - 16usize];
    ["Alignment of kvm_vmi_inject_event"][::std::mem::align_of::<kvm_vmi_inject_event>() - 8usize];
    ["Offset of field: kvm_vmi_inject_event::vcpu_id"]
        [::std::mem::offset_of!(kvm_vmi_inject_event, vcpu_id) - 0usize];
    ["Offset of field: kvm_vmi_inject_event::type_"]
        [::std::mem::offset_of!(kvm_vmi_inject_event, type_) - 4usize];
    ["Offset of field: kvm_vmi_inject_event::esr"]
        [::std::mem::offset_of!(kvm_vmi_inject_event, esr) - 8usize];
};
#[doc = " struct kvm_vmi_setup_ring - Ring setup parameters\n @vcpu_id: Target vCPU\n @flags: Reserved, must be 0\n @event_fd: IN: eventfd for kernel -> agent event notification\n @ack_fd: IN: eventfd for agent -> kernel response notification\n @ring_fd: OUT: fd to mmap for the ring page (created by kernel)\n @pad: Reserved padding"]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_setup_ring {
    pub vcpu_id: __u32,
    pub flags: __u32,
    pub event_fd: __s32,
    pub ack_fd: __s32,
    pub ring_fd: __s32,
    pub pad: __s32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_setup_ring"][::std::mem::size_of::<kvm_vmi_setup_ring>() - 24usize];
    ["Alignment of kvm_vmi_setup_ring"][::std::mem::align_of::<kvm_vmi_setup_ring>() - 4usize];
    ["Offset of field: kvm_vmi_setup_ring::vcpu_id"]
        [::std::mem::offset_of!(kvm_vmi_setup_ring, vcpu_id) - 0usize];
    ["Offset of field: kvm_vmi_setup_ring::flags"]
        [::std::mem::offset_of!(kvm_vmi_setup_ring, flags) - 4usize];
    ["Offset of field: kvm_vmi_setup_ring::event_fd"]
        [::std::mem::offset_of!(kvm_vmi_setup_ring, event_fd) - 8usize];
    ["Offset of field: kvm_vmi_setup_ring::ack_fd"]
        [::std::mem::offset_of!(kvm_vmi_setup_ring, ack_fd) - 12usize];
    ["Offset of field: kvm_vmi_setup_ring::ring_fd"]
        [::std::mem::offset_of!(kvm_vmi_setup_ring, ring_fd) - 16usize];
    ["Offset of field: kvm_vmi_setup_ring::pad"]
        [::std::mem::offset_of!(kvm_vmi_setup_ring, pad) - 20usize];
};
#[doc = " struct kvm_vmi_control_event - VM-wide event monitoring control\n @event: Event type (KVM_VMI_EVENT_*)\n @enable: 1 to enable, 0 to disable\n @flags: Reserved, must be zero.\n @pad: Reserved padding, must be zero.\n @param: Event-specific parameter\n         For CR events: cr.index, cr.onchangeonly, cr.bitmask\n         For MSR events: msr.msr, msr.onchangeonly"]
#[repr(C)]
#[derive(Copy, Clone)]
pub struct kvm_vmi_control_event {
    pub event: __u32,
    pub enable: __u32,
    pub flags: __u32,
    pub pad: __u32,
    pub __bindgen_anon_1: kvm_vmi_control_event__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union kvm_vmi_control_event__bindgen_ty_1 {
    pub cr: kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_1,
    pub msr: kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_2,
    pub pad2: [__u8; 24usize],
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_1 {
    pub index: __u8,
    pub onchangeonly: __u8,
    pub pad: [__u8; 6usize],
    pub bitmask: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::size_of::<kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_1>() - 16usize];
    ["Alignment of kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_1>() - 8usize];
    ["Offset of field: kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_1::index"]
        [::std::mem::offset_of!(kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_1, index) - 0usize];
    ["Offset of field: kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_1::onchangeonly"][::std::mem::offset_of!(
        kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_1,
        onchangeonly
    )
        - 1usize];
    ["Offset of field: kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_1::pad"]
        [::std::mem::offset_of!(kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_1, pad) - 2usize];
    ["Offset of field: kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_1::bitmask"][::std::mem::offset_of!(
        kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_1,
        bitmask
    ) - 8usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_2 {
    pub msr: __u32,
    pub onchangeonly: __u8,
    pub pad: [__u8; 3usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::size_of::<kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_2>() - 8usize];
    ["Alignment of kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::align_of::<kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_2>() - 4usize];
    ["Offset of field: kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_2::msr"]
        [::std::mem::offset_of!(kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_2, msr) - 0usize];
    ["Offset of field: kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_2::onchangeonly"][::std::mem::offset_of!(
        kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_2,
        onchangeonly
    )
        - 4usize];
    ["Offset of field: kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_2::pad"]
        [::std::mem::offset_of!(kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_2, pad) - 5usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_control_event__bindgen_ty_1"]
        [::std::mem::size_of::<kvm_vmi_control_event__bindgen_ty_1>() - 24usize];
    ["Alignment of kvm_vmi_control_event__bindgen_ty_1"]
        [::std::mem::align_of::<kvm_vmi_control_event__bindgen_ty_1>() - 8usize];
    ["Offset of field: kvm_vmi_control_event__bindgen_ty_1::cr"]
        [::std::mem::offset_of!(kvm_vmi_control_event__bindgen_ty_1, cr) - 0usize];
    ["Offset of field: kvm_vmi_control_event__bindgen_ty_1::msr"]
        [::std::mem::offset_of!(kvm_vmi_control_event__bindgen_ty_1, msr) - 0usize];
    ["Offset of field: kvm_vmi_control_event__bindgen_ty_1::pad2"]
        [::std::mem::offset_of!(kvm_vmi_control_event__bindgen_ty_1, pad2) - 0usize];
};
impl Default for kvm_vmi_control_event__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_control_event"][::std::mem::size_of::<kvm_vmi_control_event>() - 40usize];
    ["Alignment of kvm_vmi_control_event"]
        [::std::mem::align_of::<kvm_vmi_control_event>() - 8usize];
    ["Offset of field: kvm_vmi_control_event::event"]
        [::std::mem::offset_of!(kvm_vmi_control_event, event) - 0usize];
    ["Offset of field: kvm_vmi_control_event::enable"]
        [::std::mem::offset_of!(kvm_vmi_control_event, enable) - 4usize];
    ["Offset of field: kvm_vmi_control_event::flags"]
        [::std::mem::offset_of!(kvm_vmi_control_event, flags) - 8usize];
    ["Offset of field: kvm_vmi_control_event::pad"]
        [::std::mem::offset_of!(kvm_vmi_control_event, pad) - 12usize];
};
impl Default for kvm_vmi_control_event {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[doc = " struct kvm_vmi_vcpu - Generic vCPU identifier for vmi_fd ioctls"]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_vcpu {
    pub vcpu_id: __u32,
    pub pad: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_vcpu"][::std::mem::size_of::<kvm_vmi_vcpu>() - 8usize];
    ["Alignment of kvm_vmi_vcpu"][::std::mem::align_of::<kvm_vmi_vcpu>() - 4usize];
    ["Offset of field: kvm_vmi_vcpu::vcpu_id"]
        [::std::mem::offset_of!(kvm_vmi_vcpu, vcpu_id) - 0usize];
    ["Offset of field: kvm_vmi_vcpu::pad"][::std::mem::offset_of!(kvm_vmi_vcpu, pad) - 4usize];
};
#[doc = " struct kvm_vmi_view - Alternate memory view descriptor\n @view_id: View identifier. OUT on create (assigned by kernel), IN on destroy.\n           View 0 is always the default (host) view and cannot be created/destroyed.\n @flags: Reserved, must be zero.\n @default_access: Default R/W/X permissions for lazily-populated entries.\n                  Combination of KVM_VMI_ACCESS_R/W/X flags.\n @pad: Reserved padding, must be zero."]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_view {
    pub view_id: __u32,
    pub flags: __u32,
    pub default_access: __u8,
    pub pad: [__u8; 7usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_view"][::std::mem::size_of::<kvm_vmi_view>() - 16usize];
    ["Alignment of kvm_vmi_view"][::std::mem::align_of::<kvm_vmi_view>() - 4usize];
    ["Offset of field: kvm_vmi_view::view_id"]
        [::std::mem::offset_of!(kvm_vmi_view, view_id) - 0usize];
    ["Offset of field: kvm_vmi_view::flags"][::std::mem::offset_of!(kvm_vmi_view, flags) - 4usize];
    ["Offset of field: kvm_vmi_view::default_access"]
        [::std::mem::offset_of!(kvm_vmi_view, default_access) - 8usize];
    ["Offset of field: kvm_vmi_view::pad"][::std::mem::offset_of!(kvm_vmi_view, pad) - 9usize];
};
#[doc = " struct kvm_vmi_switch_view - Switch all vCPUs to a view via vmi_fd\n\n Switches every vCPU in the VM to the specified view atomically.\n For per-vCPU view switching, use the KVM_VMI_RESPONSE_SWITCH_VIEW\n flag in the ring event response."]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_switch_view {
    pub view_id: __u32,
    pub pad: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_switch_view"][::std::mem::size_of::<kvm_vmi_switch_view>() - 8usize];
    ["Alignment of kvm_vmi_switch_view"][::std::mem::align_of::<kvm_vmi_switch_view>() - 4usize];
    ["Offset of field: kvm_vmi_switch_view::view_id"]
        [::std::mem::offset_of!(kvm_vmi_switch_view, view_id) - 0usize];
    ["Offset of field: kvm_vmi_switch_view::pad"]
        [::std::mem::offset_of!(kvm_vmi_switch_view, pad) - 4usize];
};
#[doc = " struct kvm_vmi_mem_access - Memory access permissions for a view\n @view_id: Target view.\n @nr: Number of GFNs (0 or 1 for single-GFN, >1 for batch).\n\n Single-GFN mode (nr <= 1):\n   @gfn: The guest frame number.\n   @access: Combination of KVM_VMI_ACCESS_R/W/X flags.\n\n Batch mode (nr > 1):\n   @gfns_uaddr: Userspace pointer to __u64 array of GFNs.\n   @accesses_uaddr: Userspace pointer to __u8 array of access flags."]
#[repr(C)]
#[derive(Copy, Clone)]
pub struct kvm_vmi_mem_access {
    pub view_id: __u32,
    pub nr: __u32,
    pub __bindgen_anon_1: kvm_vmi_mem_access__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union kvm_vmi_mem_access__bindgen_ty_1 {
    pub __bindgen_anon_1: kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1,
    pub __bindgen_anon_2: kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_2,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1 {
    pub gfn: __u64,
    pub access: __u8,
    pub pad: [__u8; 7usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::size_of::<kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1>() - 16usize];
    ["Alignment of kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1>() - 8usize];
    ["Offset of field: kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1::gfn"]
        [::std::mem::offset_of!(kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1, gfn) - 0usize];
    ["Offset of field: kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1::access"]
        [::std::mem::offset_of!(kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1, access) - 8usize];
    ["Offset of field: kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1::pad"]
        [::std::mem::offset_of!(kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1, pad) - 9usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_2 {
    pub gfns_uaddr: __u64,
    pub accesses_uaddr: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::size_of::<kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_2>() - 16usize];
    ["Alignment of kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::align_of::<kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_2>() - 8usize];
    ["Offset of field: kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_2::gfns_uaddr"][::std::mem::offset_of!(
        kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_2,
        gfns_uaddr
    ) - 0usize];
    ["Offset of field: kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_2::accesses_uaddr"][::std::mem::offset_of!(
        kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_2,
        accesses_uaddr
    ) - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_mem_access__bindgen_ty_1"]
        [::std::mem::size_of::<kvm_vmi_mem_access__bindgen_ty_1>() - 16usize];
    ["Alignment of kvm_vmi_mem_access__bindgen_ty_1"]
        [::std::mem::align_of::<kvm_vmi_mem_access__bindgen_ty_1>() - 8usize];
};
impl Default for kvm_vmi_mem_access__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_mem_access"][::std::mem::size_of::<kvm_vmi_mem_access>() - 24usize];
    ["Alignment of kvm_vmi_mem_access"][::std::mem::align_of::<kvm_vmi_mem_access>() - 8usize];
    ["Offset of field: kvm_vmi_mem_access::view_id"]
        [::std::mem::offset_of!(kvm_vmi_mem_access, view_id) - 0usize];
    ["Offset of field: kvm_vmi_mem_access::nr"]
        [::std::mem::offset_of!(kvm_vmi_mem_access, nr) - 4usize];
};
impl Default for kvm_vmi_mem_access {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_alloc_gfn {
    pub gfn: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_alloc_gfn"][::std::mem::size_of::<kvm_vmi_alloc_gfn>() - 8usize];
    ["Alignment of kvm_vmi_alloc_gfn"][::std::mem::align_of::<kvm_vmi_alloc_gfn>() - 8usize];
    ["Offset of field: kvm_vmi_alloc_gfn::gfn"]
        [::std::mem::offset_of!(kvm_vmi_alloc_gfn, gfn) - 0usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_free_gfn {
    pub gfn: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_free_gfn"][::std::mem::size_of::<kvm_vmi_free_gfn>() - 8usize];
    ["Alignment of kvm_vmi_free_gfn"][::std::mem::align_of::<kvm_vmi_free_gfn>() - 8usize];
    ["Offset of field: kvm_vmi_free_gfn::gfn"]
        [::std::mem::offset_of!(kvm_vmi_free_gfn, gfn) - 0usize];
};
#[doc = " struct kvm_vmi_change_gfn - Remap a GFN in an alternate view\n @view_id: Target view (must not be 0).\n @pad: Reserved padding, must be zero.\n @old_gfn: The GFN whose mapping to override.\n @new_gfn: The GFN whose backing page should be used instead.\n           Set to KVM_VMI_INVALID_GFN to revert to host mapping."]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_change_gfn {
    pub view_id: __u32,
    pub pad: __u32,
    pub old_gfn: __u64,
    pub new_gfn: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_change_gfn"][::std::mem::size_of::<kvm_vmi_change_gfn>() - 24usize];
    ["Alignment of kvm_vmi_change_gfn"][::std::mem::align_of::<kvm_vmi_change_gfn>() - 8usize];
    ["Offset of field: kvm_vmi_change_gfn::view_id"]
        [::std::mem::offset_of!(kvm_vmi_change_gfn, view_id) - 0usize];
    ["Offset of field: kvm_vmi_change_gfn::pad"]
        [::std::mem::offset_of!(kvm_vmi_change_gfn, pad) - 4usize];
    ["Offset of field: kvm_vmi_change_gfn::old_gfn"]
        [::std::mem::offset_of!(kvm_vmi_change_gfn, old_gfn) - 8usize];
    ["Offset of field: kvm_vmi_change_gfn::new_gfn"]
        [::std::mem::offset_of!(kvm_vmi_change_gfn, new_gfn) - 16usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_event_mem_access {
    pub gpa: __u64,
    pub access: __u32,
    pub pad: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_event_mem_access"]
        [::std::mem::size_of::<kvm_vmi_event_mem_access>() - 16usize];
    ["Alignment of kvm_vmi_event_mem_access"]
        [::std::mem::align_of::<kvm_vmi_event_mem_access>() - 8usize];
    ["Offset of field: kvm_vmi_event_mem_access::gpa"]
        [::std::mem::offset_of!(kvm_vmi_event_mem_access, gpa) - 0usize];
    ["Offset of field: kvm_vmi_event_mem_access::access"]
        [::std::mem::offset_of!(kvm_vmi_event_mem_access, access) - 8usize];
    ["Offset of field: kvm_vmi_event_mem_access::pad"]
        [::std::mem::offset_of!(kvm_vmi_event_mem_access, pad) - 12usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_event_singlestep {
    pub gpa: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_event_singlestep"]
        [::std::mem::size_of::<kvm_vmi_event_singlestep>() - 8usize];
    ["Alignment of kvm_vmi_event_singlestep"]
        [::std::mem::align_of::<kvm_vmi_event_singlestep>() - 8usize];
    ["Offset of field: kvm_vmi_event_singlestep::gpa"]
        [::std::mem::offset_of!(kvm_vmi_event_singlestep, gpa) - 0usize];
};
#[doc = " struct kvm_vmi_ring_header - Ring page header\n @req_prod: Producer index (kernel increments after writing event)\n @req_cons: Consumer index (agent increments after reading event)\n @num_slots: Number of event slots in this ring\n @pad: Reserved padding"]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_ring_header {
    pub req_prod: __u32,
    pub req_cons: __u32,
    pub num_slots: __u32,
    pub pad: [__u32; 13usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_ring_header"][::std::mem::size_of::<kvm_vmi_ring_header>() - 64usize];
    ["Alignment of kvm_vmi_ring_header"][::std::mem::align_of::<kvm_vmi_ring_header>() - 4usize];
    ["Offset of field: kvm_vmi_ring_header::req_prod"]
        [::std::mem::offset_of!(kvm_vmi_ring_header, req_prod) - 0usize];
    ["Offset of field: kvm_vmi_ring_header::req_cons"]
        [::std::mem::offset_of!(kvm_vmi_ring_header, req_cons) - 4usize];
    ["Offset of field: kvm_vmi_ring_header::num_slots"]
        [::std::mem::offset_of!(kvm_vmi_ring_header, num_slots) - 8usize];
    ["Offset of field: kvm_vmi_ring_header::pad"]
        [::std::mem::offset_of!(kvm_vmi_ring_header, pad) - 12usize];
};
#[doc = " struct kvm_vmi_ring_event - Ring event slot\n\n Written by kernel (header + event data + regs), response area\n written by agent before signaling ack_fd.\n\n Generic events (mem_access, singlestep) are direct union members.\n Arch-specific events are grouped under the 'arch' union member."]
#[repr(C)]
#[derive(Copy, Clone)]
pub struct kvm_vmi_ring_event {
    pub type_: __u32,
    pub flags: __u32,
    pub vcpu_id: __u32,
    pub view_id: __u32,
    pub insn_len: __u8,
    pub _pad: [__u8; 3usize],
    pub response: __u32,
    pub __bindgen_anon_1: kvm_vmi_ring_event__bindgen_ty_1,
    pub regs: kvm_vmi_regs,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union kvm_vmi_ring_event__bindgen_ty_1 {
    pub mem_access: kvm_vmi_event_mem_access,
    pub singlestep: kvm_vmi_event_singlestep,
    pub arch: kvm_vmi_arch_event_data,
    pub pad2: [__u8; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_ring_event__bindgen_ty_1"]
        [::std::mem::size_of::<kvm_vmi_ring_event__bindgen_ty_1>() - 32usize];
    ["Alignment of kvm_vmi_ring_event__bindgen_ty_1"]
        [::std::mem::align_of::<kvm_vmi_ring_event__bindgen_ty_1>() - 8usize];
    ["Offset of field: kvm_vmi_ring_event__bindgen_ty_1::mem_access"]
        [::std::mem::offset_of!(kvm_vmi_ring_event__bindgen_ty_1, mem_access) - 0usize];
    ["Offset of field: kvm_vmi_ring_event__bindgen_ty_1::singlestep"]
        [::std::mem::offset_of!(kvm_vmi_ring_event__bindgen_ty_1, singlestep) - 0usize];
    ["Offset of field: kvm_vmi_ring_event__bindgen_ty_1::arch"]
        [::std::mem::offset_of!(kvm_vmi_ring_event__bindgen_ty_1, arch) - 0usize];
    ["Offset of field: kvm_vmi_ring_event__bindgen_ty_1::pad2"]
        [::std::mem::offset_of!(kvm_vmi_ring_event__bindgen_ty_1, pad2) - 0usize];
};
impl Default for kvm_vmi_ring_event__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_ring_event"][::std::mem::size_of::<kvm_vmi_ring_event>() - 416usize];
    ["Alignment of kvm_vmi_ring_event"][::std::mem::align_of::<kvm_vmi_ring_event>() - 8usize];
    ["Offset of field: kvm_vmi_ring_event::type_"]
        [::std::mem::offset_of!(kvm_vmi_ring_event, type_) - 0usize];
    ["Offset of field: kvm_vmi_ring_event::flags"]
        [::std::mem::offset_of!(kvm_vmi_ring_event, flags) - 4usize];
    ["Offset of field: kvm_vmi_ring_event::vcpu_id"]
        [::std::mem::offset_of!(kvm_vmi_ring_event, vcpu_id) - 8usize];
    ["Offset of field: kvm_vmi_ring_event::view_id"]
        [::std::mem::offset_of!(kvm_vmi_ring_event, view_id) - 12usize];
    ["Offset of field: kvm_vmi_ring_event::insn_len"]
        [::std::mem::offset_of!(kvm_vmi_ring_event, insn_len) - 16usize];
    ["Offset of field: kvm_vmi_ring_event::_pad"]
        [::std::mem::offset_of!(kvm_vmi_ring_event, _pad) - 17usize];
    ["Offset of field: kvm_vmi_ring_event::response"]
        [::std::mem::offset_of!(kvm_vmi_ring_event, response) - 20usize];
    ["Offset of field: kvm_vmi_ring_event::regs"]
        [::std::mem::offset_of!(kvm_vmi_ring_event, regs) - 56usize];
};
impl Default for kvm_vmi_ring_event {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub const KVM_CREATE_VMI_IOCTL: ::std::os::raw::c_ulong = 44777;
pub const KVM_VMI_CONTROL_EVENT_IOCTL: ::std::os::raw::c_ulong = 1076408044;
pub const KVM_VMI_ACK_EVENT_IOCTL: ::std::os::raw::c_ulong = 1074310893;
pub const KVM_VMI_SETUP_RING_IOCTL: ::std::os::raw::c_ulong = 3222843114;
pub const KVM_VMI_TEARDOWN_RING_IOCTL: ::std::os::raw::c_ulong = 1074048747;
pub const KVM_VMI_CREATE_VIEW_IOCTL: ::std::os::raw::c_ulong = 3222318830;
pub const KVM_VMI_DESTROY_VIEW_IOCTL: ::std::os::raw::c_ulong = 1074835183;
pub const KVM_VMI_SWITCH_VIEW_IOCTL: ::std::os::raw::c_ulong = 1074310896;
pub const KVM_VMI_GET_MEM_ACCESS_IOCTL: ::std::os::raw::c_ulong = 3222843121;
pub const KVM_VMI_SET_MEM_ACCESS_IOCTL: ::std::os::raw::c_ulong = 1075359474;
pub const KVM_VMI_PAUSE_VM_IOCTL: ::std::os::raw::c_ulong = 44790;
pub const KVM_VMI_UNPAUSE_VM_IOCTL: ::std::os::raw::c_ulong = 44791;
pub const KVM_VMI_PAUSE_VCPU_IOCTL: ::std::os::raw::c_ulong = 1074310904;
pub const KVM_VMI_UNPAUSE_VCPU_IOCTL: ::std::os::raw::c_ulong = 1074310905;
pub const KVM_VMI_INJECT_EVENT_IOCTL: ::std::os::raw::c_ulong = 1074835194;
pub const KVM_VMI_ALLOC_GFN_IOCTL: ::std::os::raw::c_ulong = 3221794547;
pub const KVM_VMI_FREE_GFN_IOCTL: ::std::os::raw::c_ulong = 1074310900;
pub const KVM_VMI_CHANGE_GFN_IOCTL: ::std::os::raw::c_ulong = 1075359477;
pub const KVM_VMI_EVENT_BREAKPOINT_EVAL: ::std::os::raw::c_uint = 8;
pub const KVM_VMI_NUM_EVENTS_EVAL: ::std::os::raw::c_uint = 10;
pub const KVM_VMI_EVENT_SYSREG_EVAL: ::std::os::raw::c_uint = 9;
pub const KVM_GET_ONE_REG_IOCTL: ::std::os::raw::c_ulong = 1074835115;
pub const KVM_CHECK_EXTENSION_IOCTL: ::std::os::raw::c_ulong = 44547;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_one_reg {
    pub id: __u64,
    pub addr: __u64,
}
