/* automatically generated by rust-bindgen 0.72.1 */

pub const KVM_CAP_NR_VCPUS: u32 = 9;
pub const KVM_CAP_NR_MEMSLOTS: u32 = 10;
pub const KVM_CAP_MAX_VCPUS: u32 = 66;
pub const KVM_CAP_VMI: u32 = 248;
pub const KVM_CAP_VMI_RING: u32 = 260;
pub const KVM_CAP_VMI_GUEST_MMAP: u32 = 261;
pub const KVM_CAP_VMI_PAUSE: u32 = 262;
pub const KVM_CAP_VMI_INJECT: u32 = 263;
pub const KVM_CAP_VMI_ALLOC_GFN: u32 = 264;
pub const KVM_CAP_VMI_EPT_PW: u32 = 265;
pub const KVM_VMI_EVENT_MEM_ACCESS: u32 = 0;
pub const KVM_VMI_EVENT_SINGLESTEP: u32 = 1;
pub const KVM_VMI_EVENT_ARCH_BASE: u32 = 8;
pub const KVM_VMI_CR0: u32 = 0;
pub const KVM_VMI_CR3: u32 = 3;
pub const KVM_VMI_CR4: u32 = 4;
pub const KVM_VMI_XCR0: u32 = 64;
pub const KVM_VMI_DESC_GDTR: u32 = 0;
pub const KVM_VMI_DESC_IDTR: u32 = 1;
pub const KVM_VMI_DESC_LDTR: u32 = 2;
pub const KVM_VMI_DESC_TR: u32 = 3;
pub const KVM_VMI_EVENT_TYPE_EXT_INT: u32 = 0;
pub const KVM_VMI_EVENT_TYPE_NMI: u32 = 2;
pub const KVM_VMI_EVENT_TYPE_HW_EXCEPT: u32 = 3;
pub const KVM_VMI_EVENT_TYPE_SW_INT: u32 = 4;
pub const KVM_VMI_EVENT_TYPE_PRIV_SW_INT: u32 = 5;
pub const KVM_VMI_EVENT_TYPE_SW_EXCEPT: u32 = 6;
pub const KVM_VMI_ACCESS_R: u32 = 1;
pub const KVM_VMI_ACCESS_W: u32 = 2;
pub const KVM_VMI_ACCESS_X: u32 = 4;
pub const KVM_VMI_ACCESS_PW: u32 = 8;
pub const KVM_VMI_ACCESS_RW: u32 = 3;
pub const KVM_VMI_ACCESS_RX: u32 = 5;
pub const KVM_VMI_ACCESS_WX: u32 = 6;
pub const KVM_VMI_ACCESS_RWX: u32 = 7;
pub const KVM_VMI_ACCESS_DEFAULT: u32 = 255;
pub const KVM_VMI_SHADOW_GFN_BASE: u64 = 281474943156224;
pub const KVM_VMI_RESPONSE_CONTINUE: u32 = 0;
pub const KVM_VMI_RESPONSE_DENY: u32 = 1;
pub const KVM_VMI_RESPONSE_SET_REGS: u32 = 2;
pub const KVM_VMI_RESPONSE_SINGLESTEP: u32 = 4;
pub const KVM_VMI_RESPONSE_SINGLESTEP_FAST: u32 = 8;
pub const KVM_VMI_RESPONSE_SWITCH_VIEW: u32 = 16;
pub const KVM_VMI_RESPONSE_EMULATE: u32 = 32;
pub const KVM_VMI_RESPONSE_REINJECT: u32 = 64;
pub const KVM_VMI_RESPONSE_MASK: u32 = 127;
pub type __u8 = ::std::os::raw::c_uchar;
pub type __u16 = ::std::os::raw::c_ushort;
pub type __s32 = ::std::os::raw::c_int;
pub type __u32 = ::std::os::raw::c_uint;
pub type __u64 = ::std::os::raw::c_ulonglong;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_regs {
    pub rax: __u64,
    pub rbx: __u64,
    pub rcx: __u64,
    pub rdx: __u64,
    pub rsi: __u64,
    pub rdi: __u64,
    pub rsp: __u64,
    pub rbp: __u64,
    pub r8: __u64,
    pub r9: __u64,
    pub r10: __u64,
    pub r11: __u64,
    pub r12: __u64,
    pub r13: __u64,
    pub r14: __u64,
    pub r15: __u64,
    pub rip: __u64,
    pub rflags: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_regs"][::std::mem::size_of::<kvm_regs>() - 144usize];
    ["Alignment of kvm_regs"][::std::mem::align_of::<kvm_regs>() - 8usize];
    ["Offset of field: kvm_regs::rax"][::std::mem::offset_of!(kvm_regs, rax) - 0usize];
    ["Offset of field: kvm_regs::rbx"][::std::mem::offset_of!(kvm_regs, rbx) - 8usize];
    ["Offset of field: kvm_regs::rcx"][::std::mem::offset_of!(kvm_regs, rcx) - 16usize];
    ["Offset of field: kvm_regs::rdx"][::std::mem::offset_of!(kvm_regs, rdx) - 24usize];
    ["Offset of field: kvm_regs::rsi"][::std::mem::offset_of!(kvm_regs, rsi) - 32usize];
    ["Offset of field: kvm_regs::rdi"][::std::mem::offset_of!(kvm_regs, rdi) - 40usize];
    ["Offset of field: kvm_regs::rsp"][::std::mem::offset_of!(kvm_regs, rsp) - 48usize];
    ["Offset of field: kvm_regs::rbp"][::std::mem::offset_of!(kvm_regs, rbp) - 56usize];
    ["Offset of field: kvm_regs::r8"][::std::mem::offset_of!(kvm_regs, r8) - 64usize];
    ["Offset of field: kvm_regs::r9"][::std::mem::offset_of!(kvm_regs, r9) - 72usize];
    ["Offset of field: kvm_regs::r10"][::std::mem::offset_of!(kvm_regs, r10) - 80usize];
    ["Offset of field: kvm_regs::r11"][::std::mem::offset_of!(kvm_regs, r11) - 88usize];
    ["Offset of field: kvm_regs::r12"][::std::mem::offset_of!(kvm_regs, r12) - 96usize];
    ["Offset of field: kvm_regs::r13"][::std::mem::offset_of!(kvm_regs, r13) - 104usize];
    ["Offset of field: kvm_regs::r14"][::std::mem::offset_of!(kvm_regs, r14) - 112usize];
    ["Offset of field: kvm_regs::r15"][::std::mem::offset_of!(kvm_regs, r15) - 120usize];
    ["Offset of field: kvm_regs::rip"][::std::mem::offset_of!(kvm_regs, rip) - 128usize];
    ["Offset of field: kvm_regs::rflags"][::std::mem::offset_of!(kvm_regs, rflags) - 136usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_segment {
    pub base: __u64,
    pub limit: __u32,
    pub selector: __u16,
    pub type_: __u8,
    pub present: __u8,
    pub dpl: __u8,
    pub db: __u8,
    pub s: __u8,
    pub l: __u8,
    pub g: __u8,
    pub avl: __u8,
    pub unusable: __u8,
    pub padding: __u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_segment"][::std::mem::size_of::<kvm_segment>() - 24usize];
    ["Alignment of kvm_segment"][::std::mem::align_of::<kvm_segment>() - 8usize];
    ["Offset of field: kvm_segment::base"][::std::mem::offset_of!(kvm_segment, base) - 0usize];
    ["Offset of field: kvm_segment::limit"][::std::mem::offset_of!(kvm_segment, limit) - 8usize];
    ["Offset of field: kvm_segment::selector"]
        [::std::mem::offset_of!(kvm_segment, selector) - 12usize];
    ["Offset of field: kvm_segment::type_"][::std::mem::offset_of!(kvm_segment, type_) - 14usize];
    ["Offset of field: kvm_segment::present"]
        [::std::mem::offset_of!(kvm_segment, present) - 15usize];
    ["Offset of field: kvm_segment::dpl"][::std::mem::offset_of!(kvm_segment, dpl) - 16usize];
    ["Offset of field: kvm_segment::db"][::std::mem::offset_of!(kvm_segment, db) - 17usize];
    ["Offset of field: kvm_segment::s"][::std::mem::offset_of!(kvm_segment, s) - 18usize];
    ["Offset of field: kvm_segment::l"][::std::mem::offset_of!(kvm_segment, l) - 19usize];
    ["Offset of field: kvm_segment::g"][::std::mem::offset_of!(kvm_segment, g) - 20usize];
    ["Offset of field: kvm_segment::avl"][::std::mem::offset_of!(kvm_segment, avl) - 21usize];
    ["Offset of field: kvm_segment::unusable"]
        [::std::mem::offset_of!(kvm_segment, unusable) - 22usize];
    ["Offset of field: kvm_segment::padding"]
        [::std::mem::offset_of!(kvm_segment, padding) - 23usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_dtable {
    pub base: __u64,
    pub limit: __u16,
    pub padding: [__u16; 3usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_dtable"][::std::mem::size_of::<kvm_dtable>() - 16usize];
    ["Alignment of kvm_dtable"][::std::mem::align_of::<kvm_dtable>() - 8usize];
    ["Offset of field: kvm_dtable::base"][::std::mem::offset_of!(kvm_dtable, base) - 0usize];
    ["Offset of field: kvm_dtable::limit"][::std::mem::offset_of!(kvm_dtable, limit) - 8usize];
    ["Offset of field: kvm_dtable::padding"][::std::mem::offset_of!(kvm_dtable, padding) - 10usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_sregs {
    pub cs: kvm_segment,
    pub ds: kvm_segment,
    pub es: kvm_segment,
    pub fs: kvm_segment,
    pub gs: kvm_segment,
    pub ss: kvm_segment,
    pub tr: kvm_segment,
    pub ldt: kvm_segment,
    pub gdt: kvm_dtable,
    pub idt: kvm_dtable,
    pub cr0: __u64,
    pub cr2: __u64,
    pub cr3: __u64,
    pub cr4: __u64,
    pub cr8: __u64,
    pub efer: __u64,
    pub apic_base: __u64,
    pub interrupt_bitmap: [__u64; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_sregs"][::std::mem::size_of::<kvm_sregs>() - 312usize];
    ["Alignment of kvm_sregs"][::std::mem::align_of::<kvm_sregs>() - 8usize];
    ["Offset of field: kvm_sregs::cs"][::std::mem::offset_of!(kvm_sregs, cs) - 0usize];
    ["Offset of field: kvm_sregs::ds"][::std::mem::offset_of!(kvm_sregs, ds) - 24usize];
    ["Offset of field: kvm_sregs::es"][::std::mem::offset_of!(kvm_sregs, es) - 48usize];
    ["Offset of field: kvm_sregs::fs"][::std::mem::offset_of!(kvm_sregs, fs) - 72usize];
    ["Offset of field: kvm_sregs::gs"][::std::mem::offset_of!(kvm_sregs, gs) - 96usize];
    ["Offset of field: kvm_sregs::ss"][::std::mem::offset_of!(kvm_sregs, ss) - 120usize];
    ["Offset of field: kvm_sregs::tr"][::std::mem::offset_of!(kvm_sregs, tr) - 144usize];
    ["Offset of field: kvm_sregs::ldt"][::std::mem::offset_of!(kvm_sregs, ldt) - 168usize];
    ["Offset of field: kvm_sregs::gdt"][::std::mem::offset_of!(kvm_sregs, gdt) - 192usize];
    ["Offset of field: kvm_sregs::idt"][::std::mem::offset_of!(kvm_sregs, idt) - 208usize];
    ["Offset of field: kvm_sregs::cr0"][::std::mem::offset_of!(kvm_sregs, cr0) - 224usize];
    ["Offset of field: kvm_sregs::cr2"][::std::mem::offset_of!(kvm_sregs, cr2) - 232usize];
    ["Offset of field: kvm_sregs::cr3"][::std::mem::offset_of!(kvm_sregs, cr3) - 240usize];
    ["Offset of field: kvm_sregs::cr4"][::std::mem::offset_of!(kvm_sregs, cr4) - 248usize];
    ["Offset of field: kvm_sregs::cr8"][::std::mem::offset_of!(kvm_sregs, cr8) - 256usize];
    ["Offset of field: kvm_sregs::efer"][::std::mem::offset_of!(kvm_sregs, efer) - 264usize];
    ["Offset of field: kvm_sregs::apic_base"]
        [::std::mem::offset_of!(kvm_sregs, apic_base) - 272usize];
    ["Offset of field: kvm_sregs::interrupt_bitmap"]
        [::std::mem::offset_of!(kvm_sregs, interrupt_bitmap) - 280usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_msr_entry {
    pub index: __u32,
    pub reserved: __u32,
    pub data: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_msr_entry"][::std::mem::size_of::<kvm_msr_entry>() - 16usize];
    ["Alignment of kvm_msr_entry"][::std::mem::align_of::<kvm_msr_entry>() - 8usize];
    ["Offset of field: kvm_msr_entry::index"]
        [::std::mem::offset_of!(kvm_msr_entry, index) - 0usize];
    ["Offset of field: kvm_msr_entry::reserved"]
        [::std::mem::offset_of!(kvm_msr_entry, reserved) - 4usize];
    ["Offset of field: kvm_msr_entry::data"][::std::mem::offset_of!(kvm_msr_entry, data) - 8usize];
};
#[doc = " struct kvm_vmi_inject_event - Inject exception/interrupt/NMI\n @vcpu_id: Target vCPU\n @vector: Interrupt/exception vector (0-255)\n @type: KVM_VMI_EVENT_TYPE_* (matches VMCS interruption type encoding)\n @insn_len: Instruction length (1-15) for SW_INT/SW_EXCEPT; must be 0 otherwise\n @pad: Must be 0\n @error_code: Exception error code (if has_error is set)\n @has_error: Whether error_code is valid\n @cr2: CR2 value for #PF (vector 14)"]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_inject_event {
    pub vcpu_id: __u32,
    pub vector: __u8,
    pub type_: __u8,
    pub insn_len: __u8,
    pub pad: __u8,
    pub error_code: __u32,
    pub has_error: __u32,
    pub cr2: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_inject_event"][::std::mem::size_of::<kvm_vmi_inject_event>() - 24usize];
    ["Alignment of kvm_vmi_inject_event"][::std::mem::align_of::<kvm_vmi_inject_event>() - 8usize];
    ["Offset of field: kvm_vmi_inject_event::vcpu_id"]
        [::std::mem::offset_of!(kvm_vmi_inject_event, vcpu_id) - 0usize];
    ["Offset of field: kvm_vmi_inject_event::vector"]
        [::std::mem::offset_of!(kvm_vmi_inject_event, vector) - 4usize];
    ["Offset of field: kvm_vmi_inject_event::type_"]
        [::std::mem::offset_of!(kvm_vmi_inject_event, type_) - 5usize];
    ["Offset of field: kvm_vmi_inject_event::insn_len"]
        [::std::mem::offset_of!(kvm_vmi_inject_event, insn_len) - 6usize];
    ["Offset of field: kvm_vmi_inject_event::pad"]
        [::std::mem::offset_of!(kvm_vmi_inject_event, pad) - 7usize];
    ["Offset of field: kvm_vmi_inject_event::error_code"]
        [::std::mem::offset_of!(kvm_vmi_inject_event, error_code) - 8usize];
    ["Offset of field: kvm_vmi_inject_event::has_error"]
        [::std::mem::offset_of!(kvm_vmi_inject_event, has_error) - 12usize];
    ["Offset of field: kvm_vmi_inject_event::cr2"]
        [::std::mem::offset_of!(kvm_vmi_inject_event, cr2) - 16usize];
};
#[doc = " struct kvm_vmi_regs - x86 register snapshot embedded in ring events\n\n Contains the most commonly needed registers for VMI. For exotic\n registers (FPU, XSAVE, debug regs), the agent can call standard\n KVM ioctls (KVM_GET_FPU, etc.) since vcpu->mutex is released."]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_regs {
    pub rax: __u64,
    pub rbx: __u64,
    pub rcx: __u64,
    pub rdx: __u64,
    pub rsi: __u64,
    pub rdi: __u64,
    pub rbp: __u64,
    pub rsp: __u64,
    pub r8: __u64,
    pub r9: __u64,
    pub r10: __u64,
    pub r11: __u64,
    pub r12: __u64,
    pub r13: __u64,
    pub r14: __u64,
    pub r15: __u64,
    pub rip: __u64,
    pub rflags: __u64,
    pub cr0: __u64,
    pub cr3: __u64,
    pub cr4: __u64,
    pub xcr0: __u64,
    pub cs: kvm_vmi_regs__bindgen_ty_1,
    pub ss: kvm_vmi_regs__bindgen_ty_1,
    pub ds: kvm_vmi_regs__bindgen_ty_1,
    pub es: kvm_vmi_regs__bindgen_ty_1,
    pub fs: kvm_vmi_regs__bindgen_ty_1,
    pub gs: kvm_vmi_regs__bindgen_ty_1,
    pub sysenter_cs: __u64,
    pub sysenter_esp: __u64,
    pub sysenter_eip: __u64,
    pub msr_efer: __u64,
    pub msr_star: __u64,
    pub msr_lstar: __u64,
    pub msr_cstar: __u64,
    pub msr_syscall_mask: __u64,
    pub msr_kernel_gs_base: __u64,
    pub msr_tsc_aux: __u64,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_regs__bindgen_ty_1 {
    pub base: __u64,
    pub limit: __u32,
    pub selector: __u16,
    pub ar: __u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_regs__bindgen_ty_1"]
        [::std::mem::size_of::<kvm_vmi_regs__bindgen_ty_1>() - 16usize];
    ["Alignment of kvm_vmi_regs__bindgen_ty_1"]
        [::std::mem::align_of::<kvm_vmi_regs__bindgen_ty_1>() - 8usize];
    ["Offset of field: kvm_vmi_regs__bindgen_ty_1::base"]
        [::std::mem::offset_of!(kvm_vmi_regs__bindgen_ty_1, base) - 0usize];
    ["Offset of field: kvm_vmi_regs__bindgen_ty_1::limit"]
        [::std::mem::offset_of!(kvm_vmi_regs__bindgen_ty_1, limit) - 8usize];
    ["Offset of field: kvm_vmi_regs__bindgen_ty_1::selector"]
        [::std::mem::offset_of!(kvm_vmi_regs__bindgen_ty_1, selector) - 12usize];
    ["Offset of field: kvm_vmi_regs__bindgen_ty_1::ar"]
        [::std::mem::offset_of!(kvm_vmi_regs__bindgen_ty_1, ar) - 14usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_regs"][::std::mem::size_of::<kvm_vmi_regs>() - 352usize];
    ["Alignment of kvm_vmi_regs"][::std::mem::align_of::<kvm_vmi_regs>() - 8usize];
    ["Offset of field: kvm_vmi_regs::rax"][::std::mem::offset_of!(kvm_vmi_regs, rax) - 0usize];
    ["Offset of field: kvm_vmi_regs::rbx"][::std::mem::offset_of!(kvm_vmi_regs, rbx) - 8usize];
    ["Offset of field: kvm_vmi_regs::rcx"][::std::mem::offset_of!(kvm_vmi_regs, rcx) - 16usize];
    ["Offset of field: kvm_vmi_regs::rdx"][::std::mem::offset_of!(kvm_vmi_regs, rdx) - 24usize];
    ["Offset of field: kvm_vmi_regs::rsi"][::std::mem::offset_of!(kvm_vmi_regs, rsi) - 32usize];
    ["Offset of field: kvm_vmi_regs::rdi"][::std::mem::offset_of!(kvm_vmi_regs, rdi) - 40usize];
    ["Offset of field: kvm_vmi_regs::rbp"][::std::mem::offset_of!(kvm_vmi_regs, rbp) - 48usize];
    ["Offset of field: kvm_vmi_regs::rsp"][::std::mem::offset_of!(kvm_vmi_regs, rsp) - 56usize];
    ["Offset of field: kvm_vmi_regs::r8"][::std::mem::offset_of!(kvm_vmi_regs, r8) - 64usize];
    ["Offset of field: kvm_vmi_regs::r9"][::std::mem::offset_of!(kvm_vmi_regs, r9) - 72usize];
    ["Offset of field: kvm_vmi_regs::r10"][::std::mem::offset_of!(kvm_vmi_regs, r10) - 80usize];
    ["Offset of field: kvm_vmi_regs::r11"][::std::mem::offset_of!(kvm_vmi_regs, r11) - 88usize];
    ["Offset of field: kvm_vmi_regs::r12"][::std::mem::offset_of!(kvm_vmi_regs, r12) - 96usize];
    ["Offset of field: kvm_vmi_regs::r13"][::std::mem::offset_of!(kvm_vmi_regs, r13) - 104usize];
    ["Offset of field: kvm_vmi_regs::r14"][::std::mem::offset_of!(kvm_vmi_regs, r14) - 112usize];
    ["Offset of field: kvm_vmi_regs::r15"][::std::mem::offset_of!(kvm_vmi_regs, r15) - 120usize];
    ["Offset of field: kvm_vmi_regs::rip"][::std::mem::offset_of!(kvm_vmi_regs, rip) - 128usize];
    ["Offset of field: kvm_vmi_regs::rflags"]
        [::std::mem::offset_of!(kvm_vmi_regs, rflags) - 136usize];
    ["Offset of field: kvm_vmi_regs::cr0"][::std::mem::offset_of!(kvm_vmi_regs, cr0) - 144usize];
    ["Offset of field: kvm_vmi_regs::cr3"][::std::mem::offset_of!(kvm_vmi_regs, cr3) - 152usize];
    ["Offset of field: kvm_vmi_regs::cr4"][::std::mem::offset_of!(kvm_vmi_regs, cr4) - 160usize];
    ["Offset of field: kvm_vmi_regs::xcr0"][::std::mem::offset_of!(kvm_vmi_regs, xcr0) - 168usize];
    ["Offset of field: kvm_vmi_regs::cs"][::std::mem::offset_of!(kvm_vmi_regs, cs) - 176usize];
    ["Offset of field: kvm_vmi_regs::ss"][::std::mem::offset_of!(kvm_vmi_regs, ss) - 192usize];
    ["Offset of field: kvm_vmi_regs::ds"][::std::mem::offset_of!(kvm_vmi_regs, ds) - 208usize];
    ["Offset of field: kvm_vmi_regs::es"][::std::mem::offset_of!(kvm_vmi_regs, es) - 224usize];
    ["Offset of field: kvm_vmi_regs::fs"][::std::mem::offset_of!(kvm_vmi_regs, fs) - 240usize];
    ["Offset of field: kvm_vmi_regs::gs"][::std::mem::offset_of!(kvm_vmi_regs, gs) - 256usize];
    ["Offset of field: kvm_vmi_regs::sysenter_cs"]
        [::std::mem::offset_of!(kvm_vmi_regs, sysenter_cs) - 272usize];
    ["Offset of field: kvm_vmi_regs::sysenter_esp"]
        [::std::mem::offset_of!(kvm_vmi_regs, sysenter_esp) - 280usize];
    ["Offset of field: kvm_vmi_regs::sysenter_eip"]
        [::std::mem::offset_of!(kvm_vmi_regs, sysenter_eip) - 288usize];
    ["Offset of field: kvm_vmi_regs::msr_efer"]
        [::std::mem::offset_of!(kvm_vmi_regs, msr_efer) - 296usize];
    ["Offset of field: kvm_vmi_regs::msr_star"]
        [::std::mem::offset_of!(kvm_vmi_regs, msr_star) - 304usize];
    ["Offset of field: kvm_vmi_regs::msr_lstar"]
        [::std::mem::offset_of!(kvm_vmi_regs, msr_lstar) - 312usize];
    ["Offset of field: kvm_vmi_regs::msr_cstar"]
        [::std::mem::offset_of!(kvm_vmi_regs, msr_cstar) - 320usize];
    ["Offset of field: kvm_vmi_regs::msr_syscall_mask"]
        [::std::mem::offset_of!(kvm_vmi_regs, msr_syscall_mask) - 328usize];
    ["Offset of field: kvm_vmi_regs::msr_kernel_gs_base"]
        [::std::mem::offset_of!(kvm_vmi_regs, msr_kernel_gs_base) - 336usize];
    ["Offset of field: kvm_vmi_regs::msr_tsc_aux"]
        [::std::mem::offset_of!(kvm_vmi_regs, msr_tsc_aux) - 344usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_event_cr {
    pub index: __u32,
    pub pad: __u32,
    pub old_value: __u64,
    pub new_value: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_event_cr"][::std::mem::size_of::<kvm_vmi_event_cr>() - 24usize];
    ["Alignment of kvm_vmi_event_cr"][::std::mem::align_of::<kvm_vmi_event_cr>() - 8usize];
    ["Offset of field: kvm_vmi_event_cr::index"]
        [::std::mem::offset_of!(kvm_vmi_event_cr, index) - 0usize];
    ["Offset of field: kvm_vmi_event_cr::pad"]
        [::std::mem::offset_of!(kvm_vmi_event_cr, pad) - 4usize];
    ["Offset of field: kvm_vmi_event_cr::old_value"]
        [::std::mem::offset_of!(kvm_vmi_event_cr, old_value) - 8usize];
    ["Offset of field: kvm_vmi_event_cr::new_value"]
        [::std::mem::offset_of!(kvm_vmi_event_cr, new_value) - 16usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_event_msr {
    pub index: __u32,
    pub pad: __u32,
    pub old_value: __u64,
    pub new_value: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_event_msr"][::std::mem::size_of::<kvm_vmi_event_msr>() - 24usize];
    ["Alignment of kvm_vmi_event_msr"][::std::mem::align_of::<kvm_vmi_event_msr>() - 8usize];
    ["Offset of field: kvm_vmi_event_msr::index"]
        [::std::mem::offset_of!(kvm_vmi_event_msr, index) - 0usize];
    ["Offset of field: kvm_vmi_event_msr::pad"]
        [::std::mem::offset_of!(kvm_vmi_event_msr, pad) - 4usize];
    ["Offset of field: kvm_vmi_event_msr::old_value"]
        [::std::mem::offset_of!(kvm_vmi_event_msr, old_value) - 8usize];
    ["Offset of field: kvm_vmi_event_msr::new_value"]
        [::std::mem::offset_of!(kvm_vmi_event_msr, new_value) - 16usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_event_cpuid {
    pub leaf: __u32,
    pub subleaf: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_event_cpuid"][::std::mem::size_of::<kvm_vmi_event_cpuid>() - 8usize];
    ["Alignment of kvm_vmi_event_cpuid"][::std::mem::align_of::<kvm_vmi_event_cpuid>() - 4usize];
    ["Offset of field: kvm_vmi_event_cpuid::leaf"]
        [::std::mem::offset_of!(kvm_vmi_event_cpuid, leaf) - 0usize];
    ["Offset of field: kvm_vmi_event_cpuid::subleaf"]
        [::std::mem::offset_of!(kvm_vmi_event_cpuid, subleaf) - 4usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_event_breakpoint {
    pub gpa: __u64,
    pub insn_len: __u32,
    pub pad: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_event_breakpoint"]
        [::std::mem::size_of::<kvm_vmi_event_breakpoint>() - 16usize];
    ["Alignment of kvm_vmi_event_breakpoint"]
        [::std::mem::align_of::<kvm_vmi_event_breakpoint>() - 8usize];
    ["Offset of field: kvm_vmi_event_breakpoint::gpa"]
        [::std::mem::offset_of!(kvm_vmi_event_breakpoint, gpa) - 0usize];
    ["Offset of field: kvm_vmi_event_breakpoint::insn_len"]
        [::std::mem::offset_of!(kvm_vmi_event_breakpoint, insn_len) - 8usize];
    ["Offset of field: kvm_vmi_event_breakpoint::pad"]
        [::std::mem::offset_of!(kvm_vmi_event_breakpoint, pad) - 12usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_event_debug {
    pub pending_dbg: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_event_debug"][::std::mem::size_of::<kvm_vmi_event_debug>() - 8usize];
    ["Alignment of kvm_vmi_event_debug"][::std::mem::align_of::<kvm_vmi_event_debug>() - 8usize];
    ["Offset of field: kvm_vmi_event_debug::pending_dbg"]
        [::std::mem::offset_of!(kvm_vmi_event_debug, pending_dbg) - 0usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_event_desc_access {
    pub descriptor: __u8,
    pub is_write: __u8,
    pub pad: [__u8; 6usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_event_desc_access"]
        [::std::mem::size_of::<kvm_vmi_event_desc_access>() - 8usize];
    ["Alignment of kvm_vmi_event_desc_access"]
        [::std::mem::align_of::<kvm_vmi_event_desc_access>() - 1usize];
    ["Offset of field: kvm_vmi_event_desc_access::descriptor"]
        [::std::mem::offset_of!(kvm_vmi_event_desc_access, descriptor) - 0usize];
    ["Offset of field: kvm_vmi_event_desc_access::is_write"]
        [::std::mem::offset_of!(kvm_vmi_event_desc_access, is_write) - 1usize];
    ["Offset of field: kvm_vmi_event_desc_access::pad"]
        [::std::mem::offset_of!(kvm_vmi_event_desc_access, pad) - 2usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_event_io {
    pub port: __u16,
    pub bytes: __u8,
    pub in_: __u8,
    pub string: __u8,
    pub pad: [__u8; 3usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_event_io"][::std::mem::size_of::<kvm_vmi_event_io>() - 8usize];
    ["Alignment of kvm_vmi_event_io"][::std::mem::align_of::<kvm_vmi_event_io>() - 2usize];
    ["Offset of field: kvm_vmi_event_io::port"]
        [::std::mem::offset_of!(kvm_vmi_event_io, port) - 0usize];
    ["Offset of field: kvm_vmi_event_io::bytes"]
        [::std::mem::offset_of!(kvm_vmi_event_io, bytes) - 2usize];
    ["Offset of field: kvm_vmi_event_io::in_"]
        [::std::mem::offset_of!(kvm_vmi_event_io, in_) - 3usize];
    ["Offset of field: kvm_vmi_event_io::string"]
        [::std::mem::offset_of!(kvm_vmi_event_io, string) - 4usize];
    ["Offset of field: kvm_vmi_event_io::pad"]
        [::std::mem::offset_of!(kvm_vmi_event_io, pad) - 5usize];
};
#[doc = " union kvm_vmi_arch_event_data - x86-specific event data in ring events"]
#[repr(C)]
#[derive(Copy, Clone)]
pub union kvm_vmi_arch_event_data {
    pub cr: kvm_vmi_event_cr,
    pub msr: kvm_vmi_event_msr,
    pub cpuid: kvm_vmi_event_cpuid,
    pub breakpoint: kvm_vmi_event_breakpoint,
    pub debug: kvm_vmi_event_debug,
    pub desc_access: kvm_vmi_event_desc_access,
    pub io: kvm_vmi_event_io,
    pub pad: [__u8; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_arch_event_data"][::std::mem::size_of::<kvm_vmi_arch_event_data>() - 32usize];
    ["Alignment of kvm_vmi_arch_event_data"]
        [::std::mem::align_of::<kvm_vmi_arch_event_data>() - 8usize];
    ["Offset of field: kvm_vmi_arch_event_data::cr"]
        [::std::mem::offset_of!(kvm_vmi_arch_event_data, cr) - 0usize];
    ["Offset of field: kvm_vmi_arch_event_data::msr"]
        [::std::mem::offset_of!(kvm_vmi_arch_event_data, msr) - 0usize];
    ["Offset of field: kvm_vmi_arch_event_data::cpuid"]
        [::std::mem::offset_of!(kvm_vmi_arch_event_data, cpuid) - 0usize];
    ["Offset of field: kvm_vmi_arch_event_data::breakpoint"]
        [::std::mem::offset_of!(kvm_vmi_arch_event_data, breakpoint) - 0usize];
    ["Offset of field: kvm_vmi_arch_event_data::debug"]
        [::std::mem::offset_of!(kvm_vmi_arch_event_data, debug) - 0usize];
    ["Offset of field: kvm_vmi_arch_event_data::desc_access"]
        [::std::mem::offset_of!(kvm_vmi_arch_event_data, desc_access) - 0usize];
    ["Offset of field: kvm_vmi_arch_event_data::io"]
        [::std::mem::offset_of!(kvm_vmi_arch_event_data, io) - 0usize];
    ["Offset of field: kvm_vmi_arch_event_data::pad"]
        [::std::mem::offset_of!(kvm_vmi_arch_event_data, pad) - 0usize];
};
impl Default for kvm_vmi_arch_event_data {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[doc = " struct kvm_vmi_setup_ring - Ring setup parameters\n @vcpu_id: Target vCPU\n @flags: Reserved, must be 0\n @event_fd: IN: eventfd for kernel -> agent event notification\n @ack_fd: IN: eventfd for agent -> kernel response notification\n @ring_fd: OUT: fd to mmap for the ring page (created by kernel)\n @pad: Reserved padding"]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_setup_ring {
    pub vcpu_id: __u32,
    pub flags: __u32,
    pub event_fd: __s32,
    pub ack_fd: __s32,
    pub ring_fd: __s32,
    pub pad: __s32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_setup_ring"][::std::mem::size_of::<kvm_vmi_setup_ring>() - 24usize];
    ["Alignment of kvm_vmi_setup_ring"][::std::mem::align_of::<kvm_vmi_setup_ring>() - 4usize];
    ["Offset of field: kvm_vmi_setup_ring::vcpu_id"]
        [::std::mem::offset_of!(kvm_vmi_setup_ring, vcpu_id) - 0usize];
    ["Offset of field: kvm_vmi_setup_ring::flags"]
        [::std::mem::offset_of!(kvm_vmi_setup_ring, flags) - 4usize];
    ["Offset of field: kvm_vmi_setup_ring::event_fd"]
        [::std::mem::offset_of!(kvm_vmi_setup_ring, event_fd) - 8usize];
    ["Offset of field: kvm_vmi_setup_ring::ack_fd"]
        [::std::mem::offset_of!(kvm_vmi_setup_ring, ack_fd) - 12usize];
    ["Offset of field: kvm_vmi_setup_ring::ring_fd"]
        [::std::mem::offset_of!(kvm_vmi_setup_ring, ring_fd) - 16usize];
    ["Offset of field: kvm_vmi_setup_ring::pad"]
        [::std::mem::offset_of!(kvm_vmi_setup_ring, pad) - 20usize];
};
#[doc = " struct kvm_vmi_control_event - VM-wide event monitoring control\n @event: Event type (KVM_VMI_EVENT_*)\n @enable: 1 to enable, 0 to disable\n @flags: Reserved, must be zero.\n @pad: Reserved padding, must be zero.\n @param: Event-specific parameter\n         For CR events: cr.index, cr.onchangeonly, cr.bitmask\n         For MSR events: msr.msr, msr.onchangeonly"]
#[repr(C)]
#[derive(Copy, Clone)]
pub struct kvm_vmi_control_event {
    pub event: __u32,
    pub enable: __u32,
    pub flags: __u32,
    pub pad: __u32,
    pub __bindgen_anon_1: kvm_vmi_control_event__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union kvm_vmi_control_event__bindgen_ty_1 {
    pub cr: kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_1,
    pub msr: kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_2,
    pub pad2: [__u8; 24usize],
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_1 {
    pub index: __u8,
    pub onchangeonly: __u8,
    pub pad: [__u8; 6usize],
    pub bitmask: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::size_of::<kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_1>() - 16usize];
    ["Alignment of kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_1>() - 8usize];
    ["Offset of field: kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_1::index"]
        [::std::mem::offset_of!(kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_1, index) - 0usize];
    ["Offset of field: kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_1::onchangeonly"][::std::mem::offset_of!(
        kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_1,
        onchangeonly
    )
        - 1usize];
    ["Offset of field: kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_1::pad"]
        [::std::mem::offset_of!(kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_1, pad) - 2usize];
    ["Offset of field: kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_1::bitmask"][::std::mem::offset_of!(
        kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_1,
        bitmask
    ) - 8usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_2 {
    pub msr: __u32,
    pub onchangeonly: __u8,
    pub pad: [__u8; 3usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::size_of::<kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_2>() - 8usize];
    ["Alignment of kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::align_of::<kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_2>() - 4usize];
    ["Offset of field: kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_2::msr"]
        [::std::mem::offset_of!(kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_2, msr) - 0usize];
    ["Offset of field: kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_2::onchangeonly"][::std::mem::offset_of!(
        kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_2,
        onchangeonly
    )
        - 4usize];
    ["Offset of field: kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_2::pad"]
        [::std::mem::offset_of!(kvm_vmi_control_event__bindgen_ty_1__bindgen_ty_2, pad) - 5usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_control_event__bindgen_ty_1"]
        [::std::mem::size_of::<kvm_vmi_control_event__bindgen_ty_1>() - 24usize];
    ["Alignment of kvm_vmi_control_event__bindgen_ty_1"]
        [::std::mem::align_of::<kvm_vmi_control_event__bindgen_ty_1>() - 8usize];
    ["Offset of field: kvm_vmi_control_event__bindgen_ty_1::cr"]
        [::std::mem::offset_of!(kvm_vmi_control_event__bindgen_ty_1, cr) - 0usize];
    ["Offset of field: kvm_vmi_control_event__bindgen_ty_1::msr"]
        [::std::mem::offset_of!(kvm_vmi_control_event__bindgen_ty_1, msr) - 0usize];
    ["Offset of field: kvm_vmi_control_event__bindgen_ty_1::pad2"]
        [::std::mem::offset_of!(kvm_vmi_control_event__bindgen_ty_1, pad2) - 0usize];
};
impl Default for kvm_vmi_control_event__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_control_event"][::std::mem::size_of::<kvm_vmi_control_event>() - 40usize];
    ["Alignment of kvm_vmi_control_event"]
        [::std::mem::align_of::<kvm_vmi_control_event>() - 8usize];
    ["Offset of field: kvm_vmi_control_event::event"]
        [::std::mem::offset_of!(kvm_vmi_control_event, event) - 0usize];
    ["Offset of field: kvm_vmi_control_event::enable"]
        [::std::mem::offset_of!(kvm_vmi_control_event, enable) - 4usize];
    ["Offset of field: kvm_vmi_control_event::flags"]
        [::std::mem::offset_of!(kvm_vmi_control_event, flags) - 8usize];
    ["Offset of field: kvm_vmi_control_event::pad"]
        [::std::mem::offset_of!(kvm_vmi_control_event, pad) - 12usize];
};
impl Default for kvm_vmi_control_event {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[doc = " struct kvm_vmi_vcpu - Generic vCPU identifier for vmi_fd ioctls"]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_vcpu {
    pub vcpu_id: __u32,
    pub pad: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_vcpu"][::std::mem::size_of::<kvm_vmi_vcpu>() - 8usize];
    ["Alignment of kvm_vmi_vcpu"][::std::mem::align_of::<kvm_vmi_vcpu>() - 4usize];
    ["Offset of field: kvm_vmi_vcpu::vcpu_id"]
        [::std::mem::offset_of!(kvm_vmi_vcpu, vcpu_id) - 0usize];
    ["Offset of field: kvm_vmi_vcpu::pad"][::std::mem::offset_of!(kvm_vmi_vcpu, pad) - 4usize];
};
#[doc = " struct kvm_vmi_view - Alternate memory view descriptor\n @view_id: View identifier. OUT on create (assigned by kernel), IN on destroy.\n           View 0 is always the default (host) view and cannot be created/destroyed.\n @flags: Reserved, must be zero.\n @default_access: Default R/W/X permissions for lazily-populated entries.\n                  Combination of KVM_VMI_ACCESS_R/W/X flags.\n @pad: Reserved padding, must be zero."]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_view {
    pub view_id: __u32,
    pub flags: __u32,
    pub default_access: __u8,
    pub pad: [__u8; 7usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_view"][::std::mem::size_of::<kvm_vmi_view>() - 16usize];
    ["Alignment of kvm_vmi_view"][::std::mem::align_of::<kvm_vmi_view>() - 4usize];
    ["Offset of field: kvm_vmi_view::view_id"]
        [::std::mem::offset_of!(kvm_vmi_view, view_id) - 0usize];
    ["Offset of field: kvm_vmi_view::flags"][::std::mem::offset_of!(kvm_vmi_view, flags) - 4usize];
    ["Offset of field: kvm_vmi_view::default_access"]
        [::std::mem::offset_of!(kvm_vmi_view, default_access) - 8usize];
    ["Offset of field: kvm_vmi_view::pad"][::std::mem::offset_of!(kvm_vmi_view, pad) - 9usize];
};
#[doc = " struct kvm_vmi_switch_view - Switch all vCPUs to a view via vmi_fd\n\n Switches every vCPU in the VM to the specified view atomically.\n For per-vCPU view switching, use the KVM_VMI_RESPONSE_SWITCH_VIEW\n flag in the ring event response."]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_switch_view {
    pub view_id: __u32,
    pub pad: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_switch_view"][::std::mem::size_of::<kvm_vmi_switch_view>() - 8usize];
    ["Alignment of kvm_vmi_switch_view"][::std::mem::align_of::<kvm_vmi_switch_view>() - 4usize];
    ["Offset of field: kvm_vmi_switch_view::view_id"]
        [::std::mem::offset_of!(kvm_vmi_switch_view, view_id) - 0usize];
    ["Offset of field: kvm_vmi_switch_view::pad"]
        [::std::mem::offset_of!(kvm_vmi_switch_view, pad) - 4usize];
};
#[doc = " struct kvm_vmi_mem_access - Memory access permissions for a view\n @view_id: Target view.\n @nr: Number of GFNs (0 or 1 for single-GFN, >1 for batch).\n\n Single-GFN mode (nr <= 1):\n   @gfn: The guest frame number.\n   @access: Combination of KVM_VMI_ACCESS_R/W/X flags.\n\n Batch mode (nr > 1):\n   @gfns_uaddr: Userspace pointer to __u64 array of GFNs.\n   @accesses_uaddr: Userspace pointer to __u8 array of access flags."]
#[repr(C)]
#[derive(Copy, Clone)]
pub struct kvm_vmi_mem_access {
    pub view_id: __u32,
    pub nr: __u32,
    pub __bindgen_anon_1: kvm_vmi_mem_access__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union kvm_vmi_mem_access__bindgen_ty_1 {
    pub __bindgen_anon_1: kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1,
    pub __bindgen_anon_2: kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_2,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1 {
    pub gfn: __u64,
    pub access: __u8,
    pub pad: [__u8; 7usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::size_of::<kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1>() - 16usize];
    ["Alignment of kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1>() - 8usize];
    ["Offset of field: kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1::gfn"]
        [::std::mem::offset_of!(kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1, gfn) - 0usize];
    ["Offset of field: kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1::access"]
        [::std::mem::offset_of!(kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1, access) - 8usize];
    ["Offset of field: kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1::pad"]
        [::std::mem::offset_of!(kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1, pad) - 9usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_2 {
    pub gfns_uaddr: __u64,
    pub accesses_uaddr: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::size_of::<kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_2>() - 16usize];
    ["Alignment of kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::align_of::<kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_2>() - 8usize];
    ["Offset of field: kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_2::gfns_uaddr"][::std::mem::offset_of!(
        kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_2,
        gfns_uaddr
    ) - 0usize];
    ["Offset of field: kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_2::accesses_uaddr"][::std::mem::offset_of!(
        kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_2,
        accesses_uaddr
    ) - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_mem_access__bindgen_ty_1"]
        [::std::mem::size_of::<kvm_vmi_mem_access__bindgen_ty_1>() - 16usize];
    ["Alignment of kvm_vmi_mem_access__bindgen_ty_1"]
        [::std::mem::align_of::<kvm_vmi_mem_access__bindgen_ty_1>() - 8usize];
};
impl Default for kvm_vmi_mem_access__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_mem_access"][::std::mem::size_of::<kvm_vmi_mem_access>() - 24usize];
    ["Alignment of kvm_vmi_mem_access"][::std::mem::align_of::<kvm_vmi_mem_access>() - 8usize];
    ["Offset of field: kvm_vmi_mem_access::view_id"]
        [::std::mem::offset_of!(kvm_vmi_mem_access, view_id) - 0usize];
    ["Offset of field: kvm_vmi_mem_access::nr"]
        [::std::mem::offset_of!(kvm_vmi_mem_access, nr) - 4usize];
};
impl Default for kvm_vmi_mem_access {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_alloc_gfn {
    pub gfn: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_alloc_gfn"][::std::mem::size_of::<kvm_vmi_alloc_gfn>() - 8usize];
    ["Alignment of kvm_vmi_alloc_gfn"][::std::mem::align_of::<kvm_vmi_alloc_gfn>() - 8usize];
    ["Offset of field: kvm_vmi_alloc_gfn::gfn"]
        [::std::mem::offset_of!(kvm_vmi_alloc_gfn, gfn) - 0usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_free_gfn {
    pub gfn: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_free_gfn"][::std::mem::size_of::<kvm_vmi_free_gfn>() - 8usize];
    ["Alignment of kvm_vmi_free_gfn"][::std::mem::align_of::<kvm_vmi_free_gfn>() - 8usize];
    ["Offset of field: kvm_vmi_free_gfn::gfn"]
        [::std::mem::offset_of!(kvm_vmi_free_gfn, gfn) - 0usize];
};
#[doc = " struct kvm_vmi_change_gfn - Remap a GFN in an alternate view\n @view_id: Target view (must not be 0).\n @pad: Reserved padding, must be zero.\n @old_gfn: The GFN whose mapping to override.\n @new_gfn: The GFN whose backing page should be used instead.\n           Set to KVM_VMI_INVALID_GFN to revert to host mapping."]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_change_gfn {
    pub view_id: __u32,
    pub pad: __u32,
    pub old_gfn: __u64,
    pub new_gfn: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_change_gfn"][::std::mem::size_of::<kvm_vmi_change_gfn>() - 24usize];
    ["Alignment of kvm_vmi_change_gfn"][::std::mem::align_of::<kvm_vmi_change_gfn>() - 8usize];
    ["Offset of field: kvm_vmi_change_gfn::view_id"]
        [::std::mem::offset_of!(kvm_vmi_change_gfn, view_id) - 0usize];
    ["Offset of field: kvm_vmi_change_gfn::pad"]
        [::std::mem::offset_of!(kvm_vmi_change_gfn, pad) - 4usize];
    ["Offset of field: kvm_vmi_change_gfn::old_gfn"]
        [::std::mem::offset_of!(kvm_vmi_change_gfn, old_gfn) - 8usize];
    ["Offset of field: kvm_vmi_change_gfn::new_gfn"]
        [::std::mem::offset_of!(kvm_vmi_change_gfn, new_gfn) - 16usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_event_mem_access {
    pub gpa: __u64,
    pub access: __u32,
    pub pad: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_event_mem_access"]
        [::std::mem::size_of::<kvm_vmi_event_mem_access>() - 16usize];
    ["Alignment of kvm_vmi_event_mem_access"]
        [::std::mem::align_of::<kvm_vmi_event_mem_access>() - 8usize];
    ["Offset of field: kvm_vmi_event_mem_access::gpa"]
        [::std::mem::offset_of!(kvm_vmi_event_mem_access, gpa) - 0usize];
    ["Offset of field: kvm_vmi_event_mem_access::access"]
        [::std::mem::offset_of!(kvm_vmi_event_mem_access, access) - 8usize];
    ["Offset of field: kvm_vmi_event_mem_access::pad"]
        [::std::mem::offset_of!(kvm_vmi_event_mem_access, pad) - 12usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_event_singlestep {
    pub gpa: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_event_singlestep"]
        [::std::mem::size_of::<kvm_vmi_event_singlestep>() - 8usize];
    ["Alignment of kvm_vmi_event_singlestep"]
        [::std::mem::align_of::<kvm_vmi_event_singlestep>() - 8usize];
    ["Offset of field: kvm_vmi_event_singlestep::gpa"]
        [::std::mem::offset_of!(kvm_vmi_event_singlestep, gpa) - 0usize];
};
#[doc = " struct kvm_vmi_ring_header - Ring page header\n @req_prod: Producer index (kernel increments after writing event)\n @req_cons: Consumer index (agent increments after reading event)\n @num_slots: Number of event slots in this ring\n @pad: Reserved padding"]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_ring_header {
    pub req_prod: __u32,
    pub req_cons: __u32,
    pub num_slots: __u32,
    pub pad: [__u32; 13usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_ring_header"][::std::mem::size_of::<kvm_vmi_ring_header>() - 64usize];
    ["Alignment of kvm_vmi_ring_header"][::std::mem::align_of::<kvm_vmi_ring_header>() - 4usize];
    ["Offset of field: kvm_vmi_ring_header::req_prod"]
        [::std::mem::offset_of!(kvm_vmi_ring_header, req_prod) - 0usize];
    ["Offset of field: kvm_vmi_ring_header::req_cons"]
        [::std::mem::offset_of!(kvm_vmi_ring_header, req_cons) - 4usize];
    ["Offset of field: kvm_vmi_ring_header::num_slots"]
        [::std::mem::offset_of!(kvm_vmi_ring_header, num_slots) - 8usize];
    ["Offset of field: kvm_vmi_ring_header::pad"]
        [::std::mem::offset_of!(kvm_vmi_ring_header, pad) - 12usize];
};
#[doc = " struct kvm_vmi_ring_event - Ring event slot\n\n Written by kernel (header + event data + regs), response area\n written by agent before signaling ack_fd.\n\n Generic events (mem_access, singlestep) are direct union members.\n Arch-specific events are grouped under the 'arch' union member."]
#[repr(C)]
#[derive(Copy, Clone)]
pub struct kvm_vmi_ring_event {
    pub type_: __u32,
    pub flags: __u32,
    pub vcpu_id: __u32,
    pub view_id: __u32,
    pub insn_len: __u8,
    pub _pad: [__u8; 3usize],
    pub response: __u32,
    pub __bindgen_anon_1: kvm_vmi_ring_event__bindgen_ty_1,
    pub regs: kvm_vmi_regs,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union kvm_vmi_ring_event__bindgen_ty_1 {
    pub mem_access: kvm_vmi_event_mem_access,
    pub singlestep: kvm_vmi_event_singlestep,
    pub arch: kvm_vmi_arch_event_data,
    pub pad2: [__u8; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_ring_event__bindgen_ty_1"]
        [::std::mem::size_of::<kvm_vmi_ring_event__bindgen_ty_1>() - 32usize];
    ["Alignment of kvm_vmi_ring_event__bindgen_ty_1"]
        [::std::mem::align_of::<kvm_vmi_ring_event__bindgen_ty_1>() - 8usize];
    ["Offset of field: kvm_vmi_ring_event__bindgen_ty_1::mem_access"]
        [::std::mem::offset_of!(kvm_vmi_ring_event__bindgen_ty_1, mem_access) - 0usize];
    ["Offset of field: kvm_vmi_ring_event__bindgen_ty_1::singlestep"]
        [::std::mem::offset_of!(kvm_vmi_ring_event__bindgen_ty_1, singlestep) - 0usize];
    ["Offset of field: kvm_vmi_ring_event__bindgen_ty_1::arch"]
        [::std::mem::offset_of!(kvm_vmi_ring_event__bindgen_ty_1, arch) - 0usize];
    ["Offset of field: kvm_vmi_ring_event__bindgen_ty_1::pad2"]
        [::std::mem::offset_of!(kvm_vmi_ring_event__bindgen_ty_1, pad2) - 0usize];
};
impl Default for kvm_vmi_ring_event__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_ring_event"][::std::mem::size_of::<kvm_vmi_ring_event>() - 408usize];
    ["Alignment of kvm_vmi_ring_event"][::std::mem::align_of::<kvm_vmi_ring_event>() - 8usize];
    ["Offset of field: kvm_vmi_ring_event::type_"]
        [::std::mem::offset_of!(kvm_vmi_ring_event, type_) - 0usize];
    ["Offset of field: kvm_vmi_ring_event::flags"]
        [::std::mem::offset_of!(kvm_vmi_ring_event, flags) - 4usize];
    ["Offset of field: kvm_vmi_ring_event::vcpu_id"]
        [::std::mem::offset_of!(kvm_vmi_ring_event, vcpu_id) - 8usize];
    ["Offset of field: kvm_vmi_ring_event::view_id"]
        [::std::mem::offset_of!(kvm_vmi_ring_event, view_id) - 12usize];
    ["Offset of field: kvm_vmi_ring_event::insn_len"]
        [::std::mem::offset_of!(kvm_vmi_ring_event, insn_len) - 16usize];
    ["Offset of field: kvm_vmi_ring_event::_pad"]
        [::std::mem::offset_of!(kvm_vmi_ring_event, _pad) - 17usize];
    ["Offset of field: kvm_vmi_ring_event::response"]
        [::std::mem::offset_of!(kvm_vmi_ring_event, response) - 20usize];
    ["Offset of field: kvm_vmi_ring_event::regs"]
        [::std::mem::offset_of!(kvm_vmi_ring_event, regs) - 56usize];
};
impl Default for kvm_vmi_ring_event {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub const KVM_CREATE_VMI_IOCTL: ::std::os::raw::c_ulong = 44777;
pub const KVM_VMI_CONTROL_EVENT_IOCTL: ::std::os::raw::c_ulong = 1076408044;
pub const KVM_VMI_ACK_EVENT_IOCTL: ::std::os::raw::c_ulong = 1074310893;
pub const KVM_VMI_SETUP_RING_IOCTL: ::std::os::raw::c_ulong = 3222843114;
pub const KVM_VMI_TEARDOWN_RING_IOCTL: ::std::os::raw::c_ulong = 1074048747;
pub const KVM_VMI_CREATE_VIEW_IOCTL: ::std::os::raw::c_ulong = 3222318830;
pub const KVM_VMI_DESTROY_VIEW_IOCTL: ::std::os::raw::c_ulong = 1074835183;
pub const KVM_VMI_SWITCH_VIEW_IOCTL: ::std::os::raw::c_ulong = 1074310896;
pub const KVM_VMI_GET_MEM_ACCESS_IOCTL: ::std::os::raw::c_ulong = 3222843121;
pub const KVM_VMI_SET_MEM_ACCESS_IOCTL: ::std::os::raw::c_ulong = 1075359474;
pub const KVM_VMI_PAUSE_VM_IOCTL: ::std::os::raw::c_ulong = 44790;
pub const KVM_VMI_UNPAUSE_VM_IOCTL: ::std::os::raw::c_ulong = 44791;
pub const KVM_VMI_PAUSE_VCPU_IOCTL: ::std::os::raw::c_ulong = 1074310904;
pub const KVM_VMI_UNPAUSE_VCPU_IOCTL: ::std::os::raw::c_ulong = 1074310905;
pub const KVM_VMI_INJECT_EVENT_IOCTL: ::std::os::raw::c_ulong = 1075359482;
pub const KVM_VMI_ALLOC_GFN_IOCTL: ::std::os::raw::c_ulong = 3221794547;
pub const KVM_VMI_FREE_GFN_IOCTL: ::std::os::raw::c_ulong = 1074310900;
pub const KVM_VMI_CHANGE_GFN_IOCTL: ::std::os::raw::c_ulong = 1075359477;
pub const KVM_VMI_EVENT_CR_EVAL: ::std::os::raw::c_uint = 8;
pub const KVM_VMI_EVENT_MSR_EVAL: ::std::os::raw::c_uint = 9;
pub const KVM_VMI_EVENT_CPUID_EVAL: ::std::os::raw::c_uint = 10;
pub const KVM_VMI_EVENT_BREAKPOINT_EVAL: ::std::os::raw::c_uint = 11;
pub const KVM_VMI_EVENT_DEBUG_EVAL: ::std::os::raw::c_uint = 12;
pub const KVM_VMI_EVENT_DESC_ACCESS_EVAL: ::std::os::raw::c_uint = 13;
pub const KVM_VMI_EVENT_IO_EVAL: ::std::os::raw::c_uint = 14;
pub const KVM_VMI_NUM_EVENTS_EVAL: ::std::os::raw::c_uint = 15;
pub const KVM_GET_REGS_IOCTL: ::std::os::raw::c_ulong = 2156965505;
pub const KVM_SET_REGS_IOCTL: ::std::os::raw::c_ulong = 1083223682;
pub const KVM_GET_SREGS_IOCTL: ::std::os::raw::c_ulong = 2167975555;
pub const KVM_SET_SREGS_IOCTL: ::std::os::raw::c_ulong = 1094233732;
pub const KVM_GET_MSRS_IOCTL: ::std::os::raw::c_ulong = 3221794440;
pub const KVM_SET_MSRS_IOCTL: ::std::os::raw::c_ulong = 1074310793;
pub const KVM_CHECK_EXTENSION_IOCTL: ::std::os::raw::c_ulong = 44547;
