/* automatically generated by rust-bindgen 0.72.1 */

pub const KVM_CAP_VMI: u32 = 248;
pub const KVM_CAP_VMI_RING: u32 = 260;
pub const KVM_CAP_VMI_GUEST_MMAP: u32 = 261;
pub const KVM_CAP_VMI_PAUSE: u32 = 262;
pub const KVM_CAP_VMI_INJECT: u32 = 263;
pub const KVM_CAP_VMI_ALLOC_GFN: u32 = 264;
pub const KVM_CAP_VMI_EPT_PW: u32 = 265;
pub const KVM_VMI_EVENT_MEM_ACCESS: u32 = 0;
pub const KVM_VMI_EVENT_SINGLESTEP: u32 = 1;
pub const KVM_VMI_EVENT_HYPERCALL: u32 = 2;
pub const KVM_VMI_EVENT_ARCH_BASE: u32 = 8;
pub const KVM_VMI_SYSREG_SCTLR_EL1: u32 = 0;
pub const KVM_VMI_SYSREG_TTBR0_EL1: u32 = 1;
pub const KVM_VMI_SYSREG_TTBR1_EL1: u32 = 2;
pub const KVM_VMI_SYSREG_TCR_EL1: u32 = 3;
pub const KVM_VMI_SYSREG_CONTEXTIDR_EL1: u32 = 4;
pub const KVM_VMI_SYSREG_MAIR_EL1: u32 = 5;
pub const KVM_VMI_NR_SYSREG_MONITORS: u32 = 6;
pub const KVM_VMI_INJECT_SERROR: u32 = 0;
pub const KVM_VMI_INJECT_ABORT: u32 = 1;
pub const KVM_VMI_ACCESS_R: u32 = 1;
pub const KVM_VMI_ACCESS_W: u32 = 2;
pub const KVM_VMI_ACCESS_X: u32 = 4;
pub const KVM_VMI_ACCESS_PW: u32 = 8;
pub const KVM_VMI_ACCESS_RW: u32 = 3;
pub const KVM_VMI_ACCESS_RX: u32 = 5;
pub const KVM_VMI_ACCESS_WX: u32 = 6;
pub const KVM_VMI_ACCESS_RWX: u32 = 7;
pub const KVM_VMI_ACCESS_DEFAULT: u32 = 255;
pub const KVM_VMI_SHADOW_GFN_BASE: u64 = 281474943156224;
pub const KVM_VMI_RESPONSE_CONTINUE: u32 = 0;
pub const KVM_VMI_RESPONSE_DENY: u32 = 1;
pub const KVM_VMI_RESPONSE_SET_REGS: u32 = 2;
pub const KVM_VMI_RESPONSE_SWITCH_VIEW: u32 = 4;
pub const KVM_VMI_RESPONSE_EMULATE: u32 = 8;
pub const KVM_VMI_RESPONSE_REINJECT: u32 = 16;
pub const KVM_VMI_RESPONSE_SINGLESTEP: u32 = 32;
pub const KVM_VMI_RESPONSE_SINGLESTEP_FAST: u32 = 64;
pub const KVM_VMI_RESPONSE_MASK: u32 = 127;
pub type __u8 = ::std::os::raw::c_uchar;
pub type __u16 = ::std::os::raw::c_ushort;
pub type __s32 = ::std::os::raw::c_int;
pub type __u32 = ::std::os::raw::c_uint;
pub type __u64 = ::std::os::raw::c_ulonglong;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_one_reg {
    pub id: __u64,
    pub addr: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_one_reg"][::std::mem::size_of::<kvm_one_reg>() - 16usize];
    ["Alignment of kvm_one_reg"][::std::mem::align_of::<kvm_one_reg>() - 8usize];
    ["Offset of field: kvm_one_reg::id"][::std::mem::offset_of!(kvm_one_reg, id) - 0usize];
    ["Offset of field: kvm_one_reg::addr"][::std::mem::offset_of!(kvm_one_reg, addr) - 8usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_regs {
    pub regs: [__u64; 31usize],
    pub sp_el0: __u64,
    pub sp_el1: __u64,
    pub pc: __u64,
    pub pstate: __u64,
    pub ttbr0_el1: __u64,
    pub ttbr1_el1: __u64,
    pub tcr_el1: __u64,
    pub sctlr_el1: __u64,
    pub mair_el1: __u64,
    pub vbar_el1: __u64,
    pub contextidr_el1: __u64,
    pub elr_el1: __u64,
    pub spsr_el1: __u64,
    pub esr_el1: __u64,
    pub far_el1: __u64,
    pub tpidr_el0: __u64,
    pub tpidr_el1: __u64,
    pub tpidrro_el0: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_regs"][::std::mem::size_of::<kvm_vmi_regs>() - 392usize];
    ["Alignment of kvm_vmi_regs"][::std::mem::align_of::<kvm_vmi_regs>() - 8usize];
    ["Offset of field: kvm_vmi_regs::regs"][::std::mem::offset_of!(kvm_vmi_regs, regs) - 0usize];
    ["Offset of field: kvm_vmi_regs::sp_el0"]
        [::std::mem::offset_of!(kvm_vmi_regs, sp_el0) - 248usize];
    ["Offset of field: kvm_vmi_regs::sp_el1"]
        [::std::mem::offset_of!(kvm_vmi_regs, sp_el1) - 256usize];
    ["Offset of field: kvm_vmi_regs::pc"][::std::mem::offset_of!(kvm_vmi_regs, pc) - 264usize];
    ["Offset of field: kvm_vmi_regs::pstate"]
        [::std::mem::offset_of!(kvm_vmi_regs, pstate) - 272usize];
    ["Offset of field: kvm_vmi_regs::ttbr0_el1"]
        [::std::mem::offset_of!(kvm_vmi_regs, ttbr0_el1) - 280usize];
    ["Offset of field: kvm_vmi_regs::ttbr1_el1"]
        [::std::mem::offset_of!(kvm_vmi_regs, ttbr1_el1) - 288usize];
    ["Offset of field: kvm_vmi_regs::tcr_el1"]
        [::std::mem::offset_of!(kvm_vmi_regs, tcr_el1) - 296usize];
    ["Offset of field: kvm_vmi_regs::sctlr_el1"]
        [::std::mem::offset_of!(kvm_vmi_regs, sctlr_el1) - 304usize];
    ["Offset of field: kvm_vmi_regs::mair_el1"]
        [::std::mem::offset_of!(kvm_vmi_regs, mair_el1) - 312usize];
    ["Offset of field: kvm_vmi_regs::vbar_el1"]
        [::std::mem::offset_of!(kvm_vmi_regs, vbar_el1) - 320usize];
    ["Offset of field: kvm_vmi_regs::contextidr_el1"]
        [::std::mem::offset_of!(kvm_vmi_regs, contextidr_el1) - 328usize];
    ["Offset of field: kvm_vmi_regs::elr_el1"]
        [::std::mem::offset_of!(kvm_vmi_regs, elr_el1) - 336usize];
    ["Offset of field: kvm_vmi_regs::spsr_el1"]
        [::std::mem::offset_of!(kvm_vmi_regs, spsr_el1) - 344usize];
    ["Offset of field: kvm_vmi_regs::esr_el1"]
        [::std::mem::offset_of!(kvm_vmi_regs, esr_el1) - 352usize];
    ["Offset of field: kvm_vmi_regs::far_el1"]
        [::std::mem::offset_of!(kvm_vmi_regs, far_el1) - 360usize];
    ["Offset of field: kvm_vmi_regs::tpidr_el0"]
        [::std::mem::offset_of!(kvm_vmi_regs, tpidr_el0) - 368usize];
    ["Offset of field: kvm_vmi_regs::tpidr_el1"]
        [::std::mem::offset_of!(kvm_vmi_regs, tpidr_el1) - 376usize];
    ["Offset of field: kvm_vmi_regs::tpidrro_el0"]
        [::std::mem::offset_of!(kvm_vmi_regs, tpidrro_el0) - 384usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union kvm_vmi_arch_control_data {
    pub sysreg: kvm_vmi_arch_control_data__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_arch_control_data__bindgen_ty_1 {
    pub reg: __u8,
    pub onchangeonly: __u8,
    pub pad: [__u8; 6usize],
    pub bitmask: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_arch_control_data__bindgen_ty_1"]
        [::std::mem::size_of::<kvm_vmi_arch_control_data__bindgen_ty_1>() - 16usize];
    ["Alignment of kvm_vmi_arch_control_data__bindgen_ty_1"]
        [::std::mem::align_of::<kvm_vmi_arch_control_data__bindgen_ty_1>() - 8usize];
    ["Offset of field: kvm_vmi_arch_control_data__bindgen_ty_1::reg"]
        [::std::mem::offset_of!(kvm_vmi_arch_control_data__bindgen_ty_1, reg) - 0usize];
    ["Offset of field: kvm_vmi_arch_control_data__bindgen_ty_1::onchangeonly"]
        [::std::mem::offset_of!(kvm_vmi_arch_control_data__bindgen_ty_1, onchangeonly) - 1usize];
    ["Offset of field: kvm_vmi_arch_control_data__bindgen_ty_1::pad"]
        [::std::mem::offset_of!(kvm_vmi_arch_control_data__bindgen_ty_1, pad) - 2usize];
    ["Offset of field: kvm_vmi_arch_control_data__bindgen_ty_1::bitmask"]
        [::std::mem::offset_of!(kvm_vmi_arch_control_data__bindgen_ty_1, bitmask) - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_arch_control_data"]
        [::std::mem::size_of::<kvm_vmi_arch_control_data>() - 16usize];
    ["Alignment of kvm_vmi_arch_control_data"]
        [::std::mem::align_of::<kvm_vmi_arch_control_data>() - 8usize];
    ["Offset of field: kvm_vmi_arch_control_data::sysreg"]
        [::std::mem::offset_of!(kvm_vmi_arch_control_data, sysreg) - 0usize];
};
impl Default for kvm_vmi_arch_control_data {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_event_sysreg {
    pub reg: __u32,
    pub pad: __u32,
    pub old_value: __u64,
    pub new_value: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_event_sysreg"][::std::mem::size_of::<kvm_vmi_event_sysreg>() - 24usize];
    ["Alignment of kvm_vmi_event_sysreg"][::std::mem::align_of::<kvm_vmi_event_sysreg>() - 8usize];
    ["Offset of field: kvm_vmi_event_sysreg::reg"]
        [::std::mem::offset_of!(kvm_vmi_event_sysreg, reg) - 0usize];
    ["Offset of field: kvm_vmi_event_sysreg::pad"]
        [::std::mem::offset_of!(kvm_vmi_event_sysreg, pad) - 4usize];
    ["Offset of field: kvm_vmi_event_sysreg::old_value"]
        [::std::mem::offset_of!(kvm_vmi_event_sysreg, old_value) - 8usize];
    ["Offset of field: kvm_vmi_event_sysreg::new_value"]
        [::std::mem::offset_of!(kvm_vmi_event_sysreg, new_value) - 16usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_event_breakpoint {
    pub ipa: __u64,
    pub imm: __u32,
    pub pad: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_event_breakpoint"]
        [::std::mem::size_of::<kvm_vmi_event_breakpoint>() - 16usize];
    ["Alignment of kvm_vmi_event_breakpoint"]
        [::std::mem::align_of::<kvm_vmi_event_breakpoint>() - 8usize];
    ["Offset of field: kvm_vmi_event_breakpoint::ipa"]
        [::std::mem::offset_of!(kvm_vmi_event_breakpoint, ipa) - 0usize];
    ["Offset of field: kvm_vmi_event_breakpoint::imm"]
        [::std::mem::offset_of!(kvm_vmi_event_breakpoint, imm) - 8usize];
    ["Offset of field: kvm_vmi_event_breakpoint::pad"]
        [::std::mem::offset_of!(kvm_vmi_event_breakpoint, pad) - 12usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union kvm_vmi_arch_event_data {
    pub sysreg: kvm_vmi_event_sysreg,
    pub breakpoint: kvm_vmi_event_breakpoint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_arch_event_data"][::std::mem::size_of::<kvm_vmi_arch_event_data>() - 24usize];
    ["Alignment of kvm_vmi_arch_event_data"]
        [::std::mem::align_of::<kvm_vmi_arch_event_data>() - 8usize];
    ["Offset of field: kvm_vmi_arch_event_data::sysreg"]
        [::std::mem::offset_of!(kvm_vmi_arch_event_data, sysreg) - 0usize];
    ["Offset of field: kvm_vmi_arch_event_data::breakpoint"]
        [::std::mem::offset_of!(kvm_vmi_arch_event_data, breakpoint) - 0usize];
};
impl Default for kvm_vmi_arch_event_data {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_inject_event {
    pub vcpu_id: __u32,
    pub type_: __u32,
    pub addr: __u64,
    pub esr: __u64,
    pub iabt: __u8,
    pub has_esr: __u8,
    pub fsc: __u8,
    pub write: __u8,
    pub pad: [__u8; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_inject_event"][::std::mem::size_of::<kvm_vmi_inject_event>() - 32usize];
    ["Alignment of kvm_vmi_inject_event"][::std::mem::align_of::<kvm_vmi_inject_event>() - 8usize];
    ["Offset of field: kvm_vmi_inject_event::vcpu_id"]
        [::std::mem::offset_of!(kvm_vmi_inject_event, vcpu_id) - 0usize];
    ["Offset of field: kvm_vmi_inject_event::type_"]
        [::std::mem::offset_of!(kvm_vmi_inject_event, type_) - 4usize];
    ["Offset of field: kvm_vmi_inject_event::addr"]
        [::std::mem::offset_of!(kvm_vmi_inject_event, addr) - 8usize];
    ["Offset of field: kvm_vmi_inject_event::esr"]
        [::std::mem::offset_of!(kvm_vmi_inject_event, esr) - 16usize];
    ["Offset of field: kvm_vmi_inject_event::iabt"]
        [::std::mem::offset_of!(kvm_vmi_inject_event, iabt) - 24usize];
    ["Offset of field: kvm_vmi_inject_event::has_esr"]
        [::std::mem::offset_of!(kvm_vmi_inject_event, has_esr) - 25usize];
    ["Offset of field: kvm_vmi_inject_event::fsc"]
        [::std::mem::offset_of!(kvm_vmi_inject_event, fsc) - 26usize];
    ["Offset of field: kvm_vmi_inject_event::write"]
        [::std::mem::offset_of!(kvm_vmi_inject_event, write) - 27usize];
    ["Offset of field: kvm_vmi_inject_event::pad"]
        [::std::mem::offset_of!(kvm_vmi_inject_event, pad) - 28usize];
};
#[doc = " struct kvm_vmi_setup_ring - Ring setup parameters\n @vcpu_id: Target vCPU\n @flags: Reserved, must be 0\n @event_fd: IN: eventfd for kernel -> agent event notification\n @ack_fd: IN: eventfd for agent -> kernel response notification\n @ring_fd: OUT: fd to mmap for the ring page (created by kernel)\n @pad: Reserved padding"]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_setup_ring {
    pub vcpu_id: __u32,
    pub flags: __u32,
    pub event_fd: __s32,
    pub ack_fd: __s32,
    pub ring_fd: __s32,
    pub pad: __s32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_setup_ring"][::std::mem::size_of::<kvm_vmi_setup_ring>() - 24usize];
    ["Alignment of kvm_vmi_setup_ring"][::std::mem::align_of::<kvm_vmi_setup_ring>() - 4usize];
    ["Offset of field: kvm_vmi_setup_ring::vcpu_id"]
        [::std::mem::offset_of!(kvm_vmi_setup_ring, vcpu_id) - 0usize];
    ["Offset of field: kvm_vmi_setup_ring::flags"]
        [::std::mem::offset_of!(kvm_vmi_setup_ring, flags) - 4usize];
    ["Offset of field: kvm_vmi_setup_ring::event_fd"]
        [::std::mem::offset_of!(kvm_vmi_setup_ring, event_fd) - 8usize];
    ["Offset of field: kvm_vmi_setup_ring::ack_fd"]
        [::std::mem::offset_of!(kvm_vmi_setup_ring, ack_fd) - 12usize];
    ["Offset of field: kvm_vmi_setup_ring::ring_fd"]
        [::std::mem::offset_of!(kvm_vmi_setup_ring, ring_fd) - 16usize];
    ["Offset of field: kvm_vmi_setup_ring::pad"]
        [::std::mem::offset_of!(kvm_vmi_setup_ring, pad) - 20usize];
};
#[doc = " struct kvm_vmi_control_event - VM-wide event monitoring control\n @event: Event type (KVM_VMI_EVENT_*)\n @enable: 1 to enable, 0 to disable\n @arch: Architecture-specific event parameters"]
#[repr(C)]
#[derive(Copy, Clone)]
pub struct kvm_vmi_control_event {
    pub event: __u32,
    pub enable: __u32,
    pub arch: kvm_vmi_arch_control_data,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_control_event"][::std::mem::size_of::<kvm_vmi_control_event>() - 24usize];
    ["Alignment of kvm_vmi_control_event"]
        [::std::mem::align_of::<kvm_vmi_control_event>() - 8usize];
    ["Offset of field: kvm_vmi_control_event::event"]
        [::std::mem::offset_of!(kvm_vmi_control_event, event) - 0usize];
    ["Offset of field: kvm_vmi_control_event::enable"]
        [::std::mem::offset_of!(kvm_vmi_control_event, enable) - 4usize];
    ["Offset of field: kvm_vmi_control_event::arch"]
        [::std::mem::offset_of!(kvm_vmi_control_event, arch) - 8usize];
};
impl Default for kvm_vmi_control_event {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[doc = " struct kvm_vmi_vcpu - Generic vCPU identifier for vmi_fd ioctls"]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_vcpu {
    pub vcpu_id: __u32,
    pub pad: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_vcpu"][::std::mem::size_of::<kvm_vmi_vcpu>() - 8usize];
    ["Alignment of kvm_vmi_vcpu"][::std::mem::align_of::<kvm_vmi_vcpu>() - 4usize];
    ["Offset of field: kvm_vmi_vcpu::vcpu_id"]
        [::std::mem::offset_of!(kvm_vmi_vcpu, vcpu_id) - 0usize];
    ["Offset of field: kvm_vmi_vcpu::pad"][::std::mem::offset_of!(kvm_vmi_vcpu, pad) - 4usize];
};
#[doc = " struct kvm_vmi_view - Alternate memory view descriptor\n @view_id: View identifier. OUT on create (assigned by kernel), IN on destroy.\n           View 0 is always the default (host) view and cannot be created/destroyed.\n @flags: Reserved, must be zero.\n @default_access: Default R/W/X permissions for lazily-populated entries.\n                  Combination of KVM_VMI_ACCESS_R/W/X flags.\n @pad: Reserved padding, must be zero."]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_view {
    pub view_id: __u32,
    pub flags: __u32,
    pub default_access: __u8,
    pub pad: [__u8; 7usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_view"][::std::mem::size_of::<kvm_vmi_view>() - 16usize];
    ["Alignment of kvm_vmi_view"][::std::mem::align_of::<kvm_vmi_view>() - 4usize];
    ["Offset of field: kvm_vmi_view::view_id"]
        [::std::mem::offset_of!(kvm_vmi_view, view_id) - 0usize];
    ["Offset of field: kvm_vmi_view::flags"][::std::mem::offset_of!(kvm_vmi_view, flags) - 4usize];
    ["Offset of field: kvm_vmi_view::default_access"]
        [::std::mem::offset_of!(kvm_vmi_view, default_access) - 8usize];
    ["Offset of field: kvm_vmi_view::pad"][::std::mem::offset_of!(kvm_vmi_view, pad) - 9usize];
};
#[doc = " struct kvm_vmi_switch_view - Switch all vCPUs to a view via vmi_fd\n\n Switches every vCPU in the VM to the specified view atomically.\n For per-vCPU view switching, use the KVM_VMI_RESPONSE_SWITCH_VIEW\n flag in the ring event response."]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_switch_view {
    pub view_id: __u32,
    pub pad: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_switch_view"][::std::mem::size_of::<kvm_vmi_switch_view>() - 8usize];
    ["Alignment of kvm_vmi_switch_view"][::std::mem::align_of::<kvm_vmi_switch_view>() - 4usize];
    ["Offset of field: kvm_vmi_switch_view::view_id"]
        [::std::mem::offset_of!(kvm_vmi_switch_view, view_id) - 0usize];
    ["Offset of field: kvm_vmi_switch_view::pad"]
        [::std::mem::offset_of!(kvm_vmi_switch_view, pad) - 4usize];
};
#[doc = " struct kvm_vmi_mem_access - Memory access permissions for a view\n @view_id: Target view.\n @nr: Number of GFNs (0 or 1 for single-GFN, >1 for batch).\n\n Single-GFN mode (nr <= 1):\n   @gfn: The guest frame number.\n   @access: Combination of KVM_VMI_ACCESS_R/W/X flags.\n\n Batch mode (nr > 1):\n   @gfns_uaddr: Userspace pointer to __u64 array of GFNs.\n   @accesses_uaddr: Userspace pointer to __u8 array of access flags."]
#[repr(C)]
#[derive(Copy, Clone)]
pub struct kvm_vmi_mem_access {
    pub view_id: __u32,
    pub nr: __u32,
    pub __bindgen_anon_1: kvm_vmi_mem_access__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union kvm_vmi_mem_access__bindgen_ty_1 {
    pub __bindgen_anon_1: kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1,
    pub __bindgen_anon_2: kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_2,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1 {
    pub gfn: __u64,
    pub access: __u8,
    pub pad: __u8,
    pub autostep_mask: __u16,
    pub pad2: [__u8; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::size_of::<kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1>() - 16usize];
    ["Alignment of kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1>() - 8usize];
    ["Offset of field: kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1::gfn"]
        [::std::mem::offset_of!(kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1, gfn) - 0usize];
    ["Offset of field: kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1::access"]
        [::std::mem::offset_of!(kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1, access) - 8usize];
    ["Offset of field: kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1::pad"]
        [::std::mem::offset_of!(kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1, pad) - 9usize];
    ["Offset of field: kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1::autostep_mask"][::std::mem::offset_of!(
        kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1,
        autostep_mask
    ) - 10usize];
    ["Offset of field: kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1::pad2"]
        [::std::mem::offset_of!(kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_1, pad2) - 12usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_2 {
    pub gfns_uaddr: __u64,
    pub accesses_uaddr: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::size_of::<kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_2>() - 16usize];
    ["Alignment of kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::align_of::<kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_2>() - 8usize];
    ["Offset of field: kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_2::gfns_uaddr"][::std::mem::offset_of!(
        kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_2,
        gfns_uaddr
    ) - 0usize];
    ["Offset of field: kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_2::accesses_uaddr"][::std::mem::offset_of!(
        kvm_vmi_mem_access__bindgen_ty_1__bindgen_ty_2,
        accesses_uaddr
    ) - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_mem_access__bindgen_ty_1"]
        [::std::mem::size_of::<kvm_vmi_mem_access__bindgen_ty_1>() - 16usize];
    ["Alignment of kvm_vmi_mem_access__bindgen_ty_1"]
        [::std::mem::align_of::<kvm_vmi_mem_access__bindgen_ty_1>() - 8usize];
};
impl Default for kvm_vmi_mem_access__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_mem_access"][::std::mem::size_of::<kvm_vmi_mem_access>() - 24usize];
    ["Alignment of kvm_vmi_mem_access"][::std::mem::align_of::<kvm_vmi_mem_access>() - 8usize];
    ["Offset of field: kvm_vmi_mem_access::view_id"]
        [::std::mem::offset_of!(kvm_vmi_mem_access, view_id) - 0usize];
    ["Offset of field: kvm_vmi_mem_access::nr"]
        [::std::mem::offset_of!(kvm_vmi_mem_access, nr) - 4usize];
};
impl Default for kvm_vmi_mem_access {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_alloc_gfn {
    pub gfn: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_alloc_gfn"][::std::mem::size_of::<kvm_vmi_alloc_gfn>() - 8usize];
    ["Alignment of kvm_vmi_alloc_gfn"][::std::mem::align_of::<kvm_vmi_alloc_gfn>() - 8usize];
    ["Offset of field: kvm_vmi_alloc_gfn::gfn"]
        [::std::mem::offset_of!(kvm_vmi_alloc_gfn, gfn) - 0usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_free_gfn {
    pub gfn: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_free_gfn"][::std::mem::size_of::<kvm_vmi_free_gfn>() - 8usize];
    ["Alignment of kvm_vmi_free_gfn"][::std::mem::align_of::<kvm_vmi_free_gfn>() - 8usize];
    ["Offset of field: kvm_vmi_free_gfn::gfn"]
        [::std::mem::offset_of!(kvm_vmi_free_gfn, gfn) - 0usize];
};
#[doc = " struct kvm_vmi_change_gfn - Remap a GFN in an alternate view\n @view_id: Target view (must not be 0).\n @pad: Reserved padding, must be zero.\n @old_gfn: The GFN whose mapping to override.\n @new_gfn: The GFN whose backing page should be used instead.\n           Set to KVM_VMI_INVALID_GFN to revert to host mapping."]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_change_gfn {
    pub view_id: __u32,
    pub pad: __u32,
    pub old_gfn: __u64,
    pub new_gfn: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_change_gfn"][::std::mem::size_of::<kvm_vmi_change_gfn>() - 24usize];
    ["Alignment of kvm_vmi_change_gfn"][::std::mem::align_of::<kvm_vmi_change_gfn>() - 8usize];
    ["Offset of field: kvm_vmi_change_gfn::view_id"]
        [::std::mem::offset_of!(kvm_vmi_change_gfn, view_id) - 0usize];
    ["Offset of field: kvm_vmi_change_gfn::pad"]
        [::std::mem::offset_of!(kvm_vmi_change_gfn, pad) - 4usize];
    ["Offset of field: kvm_vmi_change_gfn::old_gfn"]
        [::std::mem::offset_of!(kvm_vmi_change_gfn, old_gfn) - 8usize];
    ["Offset of field: kvm_vmi_change_gfn::new_gfn"]
        [::std::mem::offset_of!(kvm_vmi_change_gfn, new_gfn) - 16usize];
};
#[doc = " struct kvm_vmi_mem_info - Guest RAM extent\n @max_gfn: out: exclusive upper-bound GFN of guest RAM, computed as the\n           maximum of base_gfn + npages over all memslots. Frames at or above\n           this bound (but below KVM_VMI_SHADOW_GFN_BASE) are not backed by\n           guest memory, so the agent rejects reads of them instead of\n           faulting the vmi_fd mmap.\n @pad: Reserved, set to zero."]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_mem_info {
    pub max_gfn: __u64,
    pub pad: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_mem_info"][::std::mem::size_of::<kvm_vmi_mem_info>() - 16usize];
    ["Alignment of kvm_vmi_mem_info"][::std::mem::align_of::<kvm_vmi_mem_info>() - 8usize];
    ["Offset of field: kvm_vmi_mem_info::max_gfn"]
        [::std::mem::offset_of!(kvm_vmi_mem_info, max_gfn) - 0usize];
    ["Offset of field: kvm_vmi_mem_info::pad"]
        [::std::mem::offset_of!(kvm_vmi_mem_info, pad) - 8usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_event_mem_access {
    pub gpa: __u64,
    pub access: __u32,
    pub pad: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_event_mem_access"]
        [::std::mem::size_of::<kvm_vmi_event_mem_access>() - 16usize];
    ["Alignment of kvm_vmi_event_mem_access"]
        [::std::mem::align_of::<kvm_vmi_event_mem_access>() - 8usize];
    ["Offset of field: kvm_vmi_event_mem_access::gpa"]
        [::std::mem::offset_of!(kvm_vmi_event_mem_access, gpa) - 0usize];
    ["Offset of field: kvm_vmi_event_mem_access::access"]
        [::std::mem::offset_of!(kvm_vmi_event_mem_access, access) - 8usize];
    ["Offset of field: kvm_vmi_event_mem_access::pad"]
        [::std::mem::offset_of!(kvm_vmi_event_mem_access, pad) - 12usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_event_singlestep {
    pub gpa: __u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_event_singlestep"]
        [::std::mem::size_of::<kvm_vmi_event_singlestep>() - 8usize];
    ["Alignment of kvm_vmi_event_singlestep"]
        [::std::mem::align_of::<kvm_vmi_event_singlestep>() - 8usize];
    ["Offset of field: kvm_vmi_event_singlestep::gpa"]
        [::std::mem::offset_of!(kvm_vmi_event_singlestep, gpa) - 0usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_event_hypercall {
    pub imm: __u32,
    pub pad: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_event_hypercall"][::std::mem::size_of::<kvm_vmi_event_hypercall>() - 8usize];
    ["Alignment of kvm_vmi_event_hypercall"]
        [::std::mem::align_of::<kvm_vmi_event_hypercall>() - 4usize];
    ["Offset of field: kvm_vmi_event_hypercall::imm"]
        [::std::mem::offset_of!(kvm_vmi_event_hypercall, imm) - 0usize];
    ["Offset of field: kvm_vmi_event_hypercall::pad"]
        [::std::mem::offset_of!(kvm_vmi_event_hypercall, pad) - 4usize];
};
#[doc = " struct kvm_vmi_ring_header - Ring page header\n @req_prod: Producer index (kernel increments after writing event)\n @req_cons: Consumer index (agent increments after reading event)\n @num_slots: Number of event slots in this ring\n @pad: Reserved padding"]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct kvm_vmi_ring_header {
    pub req_prod: __u32,
    pub req_cons: __u32,
    pub num_slots: __u32,
    pub pad: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_ring_header"][::std::mem::size_of::<kvm_vmi_ring_header>() - 16usize];
    ["Alignment of kvm_vmi_ring_header"][::std::mem::align_of::<kvm_vmi_ring_header>() - 4usize];
    ["Offset of field: kvm_vmi_ring_header::req_prod"]
        [::std::mem::offset_of!(kvm_vmi_ring_header, req_prod) - 0usize];
    ["Offset of field: kvm_vmi_ring_header::req_cons"]
        [::std::mem::offset_of!(kvm_vmi_ring_header, req_cons) - 4usize];
    ["Offset of field: kvm_vmi_ring_header::num_slots"]
        [::std::mem::offset_of!(kvm_vmi_ring_header, num_slots) - 8usize];
    ["Offset of field: kvm_vmi_ring_header::pad"]
        [::std::mem::offset_of!(kvm_vmi_ring_header, pad) - 12usize];
};
#[doc = " struct kvm_vmi_ring_event - Ring event slot\n\n Written by kernel (header + event data + regs), response area\n written by agent before signaling ack_fd.\n\n Generic events (mem_access, singlestep) are direct union members.\n Arch-specific events are grouped under the 'arch' union member."]
#[repr(C)]
#[derive(Copy, Clone)]
pub struct kvm_vmi_ring_event {
    pub type_: __u32,
    pub flags: __u32,
    pub vcpu_id: __u32,
    pub view_id: __u32,
    pub insn_len: __u8,
    pub _pad: [__u8; 3usize],
    pub response: __u32,
    pub __bindgen_anon_1: kvm_vmi_ring_event__bindgen_ty_1,
    pub regs: kvm_vmi_regs,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union kvm_vmi_ring_event__bindgen_ty_1 {
    pub mem_access: kvm_vmi_event_mem_access,
    pub singlestep: kvm_vmi_event_singlestep,
    pub hypercall: kvm_vmi_event_hypercall,
    pub arch: kvm_vmi_arch_event_data,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_ring_event__bindgen_ty_1"]
        [::std::mem::size_of::<kvm_vmi_ring_event__bindgen_ty_1>() - 24usize];
    ["Alignment of kvm_vmi_ring_event__bindgen_ty_1"]
        [::std::mem::align_of::<kvm_vmi_ring_event__bindgen_ty_1>() - 8usize];
    ["Offset of field: kvm_vmi_ring_event__bindgen_ty_1::mem_access"]
        [::std::mem::offset_of!(kvm_vmi_ring_event__bindgen_ty_1, mem_access) - 0usize];
    ["Offset of field: kvm_vmi_ring_event__bindgen_ty_1::singlestep"]
        [::std::mem::offset_of!(kvm_vmi_ring_event__bindgen_ty_1, singlestep) - 0usize];
    ["Offset of field: kvm_vmi_ring_event__bindgen_ty_1::hypercall"]
        [::std::mem::offset_of!(kvm_vmi_ring_event__bindgen_ty_1, hypercall) - 0usize];
    ["Offset of field: kvm_vmi_ring_event__bindgen_ty_1::arch"]
        [::std::mem::offset_of!(kvm_vmi_ring_event__bindgen_ty_1, arch) - 0usize];
};
impl Default for kvm_vmi_ring_event__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of kvm_vmi_ring_event"][::std::mem::size_of::<kvm_vmi_ring_event>() - 440usize];
    ["Alignment of kvm_vmi_ring_event"][::std::mem::align_of::<kvm_vmi_ring_event>() - 8usize];
    ["Offset of field: kvm_vmi_ring_event::type_"]
        [::std::mem::offset_of!(kvm_vmi_ring_event, type_) - 0usize];
    ["Offset of field: kvm_vmi_ring_event::flags"]
        [::std::mem::offset_of!(kvm_vmi_ring_event, flags) - 4usize];
    ["Offset of field: kvm_vmi_ring_event::vcpu_id"]
        [::std::mem::offset_of!(kvm_vmi_ring_event, vcpu_id) - 8usize];
    ["Offset of field: kvm_vmi_ring_event::view_id"]
        [::std::mem::offset_of!(kvm_vmi_ring_event, view_id) - 12usize];
    ["Offset of field: kvm_vmi_ring_event::insn_len"]
        [::std::mem::offset_of!(kvm_vmi_ring_event, insn_len) - 16usize];
    ["Offset of field: kvm_vmi_ring_event::_pad"]
        [::std::mem::offset_of!(kvm_vmi_ring_event, _pad) - 17usize];
    ["Offset of field: kvm_vmi_ring_event::response"]
        [::std::mem::offset_of!(kvm_vmi_ring_event, response) - 20usize];
    ["Offset of field: kvm_vmi_ring_event::regs"]
        [::std::mem::offset_of!(kvm_vmi_ring_event, regs) - 48usize];
};
impl Default for kvm_vmi_ring_event {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub const kvm_sys_KVM_CREATE_VMI: ::std::os::raw::c_ulong = 44777;
pub const kvm_sys_KVM_VMI_SETUP_RING: ::std::os::raw::c_ulong = 3222843114;
pub const kvm_sys_KVM_VMI_TEARDOWN_RING: ::std::os::raw::c_ulong = 1074048747;
pub const kvm_sys_KVM_VMI_ACK_EVENT: ::std::os::raw::c_ulong = 1074310892;
pub const kvm_sys_KVM_VMI_CONTROL_EVENT: ::std::os::raw::c_ulong = 1075359469;
pub const kvm_sys_KVM_VMI_PAUSE_VM: ::std::os::raw::c_ulong = 44782;
pub const kvm_sys_KVM_VMI_UNPAUSE_VM: ::std::os::raw::c_ulong = 44783;
pub const kvm_sys_KVM_VMI_PAUSE_VCPU: ::std::os::raw::c_ulong = 1074310896;
pub const kvm_sys_KVM_VMI_UNPAUSE_VCPU: ::std::os::raw::c_ulong = 1074310897;
pub const kvm_sys_KVM_VMI_INJECT_EVENT: ::std::os::raw::c_ulong = 1075883762;
pub const kvm_sys_KVM_VMI_CREATE_VIEW: ::std::os::raw::c_ulong = 3222318835;
pub const kvm_sys_KVM_VMI_DESTROY_VIEW: ::std::os::raw::c_ulong = 1074835188;
pub const kvm_sys_KVM_VMI_SWITCH_VIEW: ::std::os::raw::c_ulong = 1074310901;
pub const kvm_sys_KVM_VMI_GET_MEM_ACCESS: ::std::os::raw::c_ulong = 3222843126;
pub const kvm_sys_KVM_VMI_SET_MEM_ACCESS: ::std::os::raw::c_ulong = 1075359479;
pub const kvm_sys_KVM_VMI_ALLOC_GFN: ::std::os::raw::c_ulong = 3221794552;
pub const kvm_sys_KVM_VMI_FREE_GFN: ::std::os::raw::c_ulong = 1074310905;
pub const kvm_sys_KVM_VMI_CHANGE_GFN: ::std::os::raw::c_ulong = 1075359482;
pub const kvm_sys_KVM_VMI_GET_MEM_INFO: ::std::os::raw::c_ulong = 2148577019;
pub const kvm_sys_KVM_GET_ONE_REG: ::std::os::raw::c_ulong = 1074835115;
pub const kvm_sys_KVM_SET_ONE_REG: ::std::os::raw::c_ulong = 1074835116;
pub const kvm_sys_KVM_VMI_EVENT_SYSREG: ::std::os::raw::c_uint = 8;
pub const kvm_sys_KVM_VMI_EVENT_BREAKPOINT: ::std::os::raw::c_uint = 9;
pub const kvm_sys_KVM_VMI_INVALID_GFN: ::std::os::raw::c_longlong = -1;
